from django.contrib import admin

from .models import Land_taxes_collected, Land_yield, Total_tax, Total_economic_output, Total_revenue, Diding_taxes, Salt_tax, Tariff_and_transit, Misc_incomes, Total_expenditure, Balance, Lijin, Maritime_custom, Other_incomes, Revenue_official, Revenue_real, Gdp_total, Gdp_growth_rate, Shares_of_world_gdp, Gdp_per_capita, Rate_of_gdp_per_capita_growth, Wages, Annual_wages, Rate_of_return, Famine_event, Disease_event, Jinshi_degrees_awarded, Examination, Taiping_rebellion, Worker_wage

admin.site.register(Land_taxes_collected)
admin.site.register(Land_yield)
admin.site.register(Total_tax)
admin.site.register(Total_economic_output)
admin.site.register(Total_revenue)
admin.site.register(Diding_taxes)
admin.site.register(Salt_tax)
admin.site.register(Tariff_and_transit)
admin.site.register(Misc_incomes)
admin.site.register(Total_expenditure)
admin.site.register(Balance)
admin.site.register(Lijin)
admin.site.register(Maritime_custom)
admin.site.register(Other_incomes)
admin.site.register(Revenue_official)
admin.site.register(Revenue_real)
admin.site.register(Gdp_total)
admin.site.register(Gdp_growth_rate)
admin.site.register(Shares_of_world_gdp)
admin.site.register(Gdp_per_capita)
admin.site.register(Rate_of_gdp_per_capita_growth)
admin.site.register(Wages)
admin.site.register(Annual_wages)
admin.site.register(Rate_of_return)
admin.site.register(Famine_event)
admin.site.register(Disease_event)
admin.site.register(Jinshi_degrees_awarded)
admin.site.register(Examination)
admin.site.register(Taiping_rebellion)
admin.site.register(Worker_wage)
