# Generated by Django 4.0.3 on 2023-05-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlatl',
            name='atlatl',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='battle_axe',
            name='battle_axe',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='breastplate',
            name='breastplate',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='bronze',
            name='bronze',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='camel',
            name='camel',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='chainmail',
            name='chainmail',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='complex_fortification',
            name='complex_fortification',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='composite_bow',
            name='composite_bow',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='copper',
            name='copper',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='crossbow',
            name='crossbow',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='dagger',
            name='dagger',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='ditch',
            name='ditch',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='dog',
            name='dog',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='donkey',
            name='donkey',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='earth_rampart',
            name='earth_rampart',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='elephant',
            name='elephant',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='fortified_camp',
            name='fortified_camp',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='gunpowder_siege_artillery',
            name='gunpowder_siege_artillery',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='handheld_firearm',
            name='handheld_firearm',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='helmet',
            name='helmet',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='horse',
            name='horse',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='iron',
            name='iron',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='javelin',
            name='javelin',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='laminar_armor',
            name='laminar_armor',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='leather_cloth',
            name='leather_cloth',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='limb_protection',
            name='limb_protection',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='merchant_ships_pressed_into_service',
            name='merchant_ships_pressed_into_service',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='moat',
            name='moat',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='modern_fortification',
            name='modern_fortification',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='plate_armor',
            name='plate_armor',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='polearm',
            name='polearm',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='scaled_armor',
            name='scaled_armor',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='self_bow',
            name='self_bow',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='settlements_in_a_defensive_position',
            name='settlements_in_a_defensive_position',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='shield',
            name='shield',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='sling',
            name='sling',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='sling_siege_engine',
            name='sling_siege_engine',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='small_vessels_canoes_etc',
            name='small_vessels_canoes_etc',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='spear',
            name='spear',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='specialized_military_vessel',
            name='specialized_military_vessel',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='steel',
            name='steel',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='stone_walls_mortared',
            name='stone_walls_mortared',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='stone_walls_non_mortared',
            name='stone_walls_non_mortared',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='sword',
            name='sword',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='tension_siege_engine',
            name='tension_siege_engine',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='war_club',
            name='war_club',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='wood_bark_etc',
            name='wood_bark_etc',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='wooden_palisade',
            name='wooden_palisade',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('unknown', 'unknown'), ('A~P', 'Transitional (Absent -> Present)'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
    ]
