# Generated by Django 4.0.3 on 2024-03-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_alter_polity_alternate_religion_family_alternate_religion_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polity_alternate_religion',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_alternate_religion_family',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_alternate_religion_genus',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_alternative_name',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_capital',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_degree_of_centralization',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_duration',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_editor',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_expert',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_language',
            name='language',
            field=models.CharField(choices=[('Polish', 'Polish'), ('Pashto', 'Pashto'), ('Persian', 'Persian'), ('Greek', 'Greek'), ('Bactrian', 'Bactrian'), ('Sogdian', 'Sogdian'), ('Pahlavi', 'Pahlavi'), ('Brahmi', 'Brahmi'), ('Kharoshthi', 'Kharoshthi'), ('Tocharian', 'Tocharian'), ('Chinese', 'Chinese'), ('archaic Chinese', 'archaic Chinese'), ('Xiangxi', 'Xiangxi'), ('Qiandong', 'Qiandong'), ('Chuanqiandian', 'Chuanqiandian'), ('Hmong-Mien', 'Hmong-Mien'), ('Hmongic', 'Hmongic'), ('Middle Chinese', 'Middle Chinese'), ('Jurchen', 'Jurchen'), ('Khitan', 'Khitan'), ('Xianbei', 'Xianbei'), ('Manchu language', 'Manchu language'), ('Mongolian language', 'Mongolian language'), ('Atanque', 'Atanque'), ('Shuar', 'Shuar'), ('Arabic', 'Arabic'), ('suspected unknown', 'suspected unknown'), ('NO_VALUE_ON_WIKI', 'NO_VALUE_ON_WIKI'), ('Demotic', 'Demotic'), ('Ancient Egyptian', 'Ancient Egyptian'), ('Late Egyptian', 'Late Egyptian'), ('demotic Egyptian', 'demotic Egyptian'), ('Castilian Spanish', 'Castilian Spanish'), ('Chuukese', 'Chuukese'), ('French', 'French'), ('Langues dOil', 'Langues dOil'), ('Occitan', 'Occitan'), ('Latin', 'Latin'), ('Old Frankish', 'Old Frankish'), ('Germanic', 'Germanic'), ('Gallic', 'Gallic'), ('Gaulish', 'Gaulish'), ('English', 'English'), ('Akan', 'Akan'), ('Twi', 'Twi'), ('Doric Greek', 'Doric Greek'), ('Minoan', 'Minoan'), ('Early Greek', 'Early Greek'), ('Eteocretan', 'Eteocretan'), ('Old Hawaiian', 'Old Hawaiian'), ('Hawaiian', 'Hawaiian'), ('Iban', 'Iban'), ('Sanskrit', 'Sanskrit'), ('Old Javanese', 'Old Javanese'), ('Middle Javanese', 'Middle Javanese'), ('Javanese', 'Javanese'), ('Canaanite', 'Canaanite'), ('Aramaic', 'Aramaic'), ('Hebrew', 'Hebrew'), ('Kannada', 'Kannada'), ('Urdu', 'Urdu'), ('A’chik', 'A’chik'), ('Prakrit', 'Prakrit'), ('Telugu', 'Telugu'), ('Tamil', 'Tamil'), ('Akkadian', 'Akkadian'), ('Sumerian', 'Sumerian'), ('Amorite', 'Amorite'), ('Old Babylonian', 'Old Babylonian'), ('Mesopotamian Religions', 'Mesopotamian Religions'), ('Old Persian', 'Old Persian'), ('Elamite', 'Elamite'), ('Egyptian', 'Egyptian'), ('Old Elamite', 'Old Elamite'), ('Mongolian', 'Mongolian'), ('native Iranian languages', 'native Iranian languages'), ('Turkic', 'Turkic'), ('Turkish', 'Turkish'), ('Babylonian', 'Babylonian'), ('Hurrian', 'Hurrian'), ('Proto-Elamite', 'Proto-Elamite'), ('Old Norse', 'Old Norse'), ('Italian', 'Italian'), ('Middle Japanese', 'Middle Japanese'), ('Old Japanese', 'Old Japanese'), ('Late Old Japanese', 'Late Old Japanese'), ('Japanese', 'Japanese'), ('Early Modern Japanese', 'Early Modern Japanese'), ('Old Turkic', 'Old Turkic'), ('Iranian', 'Iranian'), ('Old Khmer', 'Old Khmer'), ('Mon', 'Mon'), ('Tai', 'Tai'), ('Khmer', 'Khmer'), ('Pali', 'Pali'), ('Phoenician', 'Phoenician'), ('Berber', 'Berber'), ('Spanish', 'Spanish'), ('Portuguese', 'Portuguese'), ('Bambara', 'Bambara'), ('Mande', 'Mande'), ('Songhay', 'Songhay'), ('Russian', 'Russian'), ('Georgian', 'Georgian'), ('Armenian', 'Armenian'), ('Kereid', 'Kereid'), ('Tatar', 'Tatar'), ('Naimans', 'Naimans'), ('Khalkha', 'Khalkha'), ('Rouran', 'Rouran'), ('Xiongnu', 'Xiongnu'), ('Oirat', 'Oirat'), ('Zapotec', 'Zapotec'), ('Icelandic', 'Icelandic'), ('Aymara', 'Aymara'), ('Puquina', 'Puquina'), ('Quechua', 'Quechua'), ('Orokaiva', 'Orokaiva'), ('unknown', 'unknown'), ('Sindhi', 'Sindhi'), ('Punjabi', 'Punjabi'), ('Sakha (Yakut)', 'Sakha (Yakut)'), ('Merotic', 'Merotic'), ('Coptic', 'Coptic'), ('Thai', 'Thai'), ('Proto-Indo-European language', 'Proto-Indo-European language'), ('Nesite', 'Nesite'), ('Luwian', 'Luwian'), ('Hattic', 'Hattic'), ('Hittite', 'Hittite'), ('Old Assyrian dialect of Akkadian', 'Old Assyrian dialect of Akkadian'), ('Indo-European language', 'Indo-European language'), ('Lydian', 'Lydian'), ('Ottoman Turkish', 'Ottoman Turkish'), ('Phrygian', 'Phrygian'), ('Miami Illinois', 'Miami Illinois'), ('Cayuga', 'Cayuga'), ('Mohawk', 'Mohawk'), ('Oneida', 'Oneida'), ('Onondaga', 'Onondaga'), ('Seneca', 'Seneca'), ('Tuscarora', 'Tuscarora'), ('Middle Mongolian', 'Middle Mongolian'), ('Ancient Iranian', 'Ancient Iranian'), ('Chagatai Turkish', 'Chagatai Turkish'), ('Sabaic', 'Sabaic'), ('Mainic', 'Mainic'), ('Qatabanic', 'Qatabanic'), ('Hadramawtic', 'Hadramawtic'), ('Old Arabic', 'Old Arabic'), ('Susu', 'Susu'), ('Koranko', 'Koranko'), ('Limba', 'Limba'), ('Temne', 'Temne'), ('Bullom', 'Bullom'), ('Loko', 'Loko'), ('Manding', 'Manding'), ('Krio', 'Krio'), ('Pulaar', 'Pulaar'), ('Kissi', 'Kissi'), ('Krim', 'Krim'), ('Vai', 'Vai'), ('Mossi', 'Mossi'), ('Shona', 'Shona'), ('Sinhala', 'Sinhala'), ('Dutch', 'Dutch'), ('Sinhalese', 'Sinhalese'), ('Oromo', 'Oromo'), ('Harari', 'Harari'), ('Argobba', 'Argobba'), ('Maay', 'Maay'), ('Somali', 'Somali'), ('Harla', 'Harla'), ('Hadiyya', 'Hadiyya'), ('Tigrinya', 'Tigrinya'), ('Funj', 'Funj'), ('Kafa', 'Kafa'), ('Yemsa', 'Yemsa'), ('Qafar', 'Qafar'), ('Proto-Yoruba', 'Proto-Yoruba'), ('Yoruba', 'Yoruba'), ('Bini', 'Bini'), ('Jukun', 'Jukun'), ('Ajagbe', 'Ajagbe'), ('Proto-Yoruboid', 'Proto-Yoruboid'), ('Sokoto', 'Sokoto'), ('Hausa', 'Hausa'), ('Idoma', 'Idoma'), ('Igbo', 'Igbo'), ('Nri', 'Nri'), ('Kanuri', 'Kanuri'), ('Kanembu', 'Kanembu'), ('Fongbe', 'Fongbe'), ('Wolof', 'Wolof'), ('Sereer', 'Sereer'), ('Fula', 'Fula'), ('Luganda', 'Luganda'), ('Kinyambo', 'Kinyambo'), ('Kinyarwanda', 'Kinyarwanda'), ('Runyankore', 'Runyankore'), ('Kirundi', 'Kirundi'), ('Fipa', 'Fipa'), ('Haya', 'Haya'), ('Old Tamil', 'Old Tamil'), ('Efik-Ibibio', 'Efik-Ibibio'), ('Hungarian', 'Hungarian'), ('Native languages', 'Native languages'), ('German', 'German'), ('Czech', 'Czech'), ('Lombardic', 'Lombardic'), ('Pukina / Puquina', 'Pukina / Puquina'), ('Old English', 'Old English'), ('Middle-Modern Persian', 'Middle-Modern Persian'), ('Anglo-Norman', 'Anglo-Norman'), ('Pictish', 'Pictish')], max_length=500),
        ),
        migrations.AlterField(
            model_name='polity_language',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_language_genus',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_linguistic_family',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_original_name',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_peak_years',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_preceding_entity',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_relationship_to_preceding_entity',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_religion',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_religion_family',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_religion_genus',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_religious_tradition',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_research_assistant',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_scale_of_supracultural_interaction',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_succeeding_entity',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_supracultural_entity',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_suprapolity_relations',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='polity_utm_zone',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
    ]
