# Generated by Django 4.0.3 on 2022-06-07 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_variablehierarchy'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variablehierarchy',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='variablehierarchy',
            name='is_verified',
        ),
    ]
