# Generated by Django 4.0.3 on 2022-06-10 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_variablehierarchy_is_verified'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variablehierarchy',
            unique_together={('name', 'section', 'subsection')},
        ),
    ]
