# Generated by Django 4.0.3 on 2022-08-29 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_citation_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citation', to='core.reference'),
        ),
    ]
