# Generated by Django 4.0.3 on 2022-08-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_citation_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='page_from',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='citation',
            name='page_to',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
