# Generated by Django 4.0.3 on 2022-08-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_citation_page_from_alter_citation_page_to'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='citation',
            name='No_PAGE_FROM',
        ),
        migrations.RemoveConstraint(
            model_name='citation',
            name='No_PAGE_TO',
        ),
        migrations.AddConstraint(
            model_name='citation',
            constraint=models.UniqueConstraint(condition=models.Q(('page_to__isnull', True)), fields=('ref', 'page_from'), name='No_PAGE_FROM'),
        ),
        migrations.AddConstraint(
            model_name='citation',
            constraint=models.UniqueConstraint(condition=models.Q(('page_from__isnull', True)), fields=('ref', 'page_to'), name='No_PAGE_TO'),
        ),
    ]
