# Generated by Django 4.0.3 on 2022-08-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_citation_no_page_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='page_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citation',
            name='page_to',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
