# Generated by Django 4.0.3 on 2022-09-01 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_variablehierarchy_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='url_link',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
