# Generated by Django 4.0.3 on 2022-05-31 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reference_long_name_alter_reference_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variablehierarchys', to='core.section')),
                ('subsection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variablehierarchys', to='core.subsection')),
            ],
        ),
    ]
