# Generated by Django 4.0.3 on 2022-06-07 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_variablehierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variablehierarchy',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variablehierarchys', to='core.section'),
        ),
        migrations.AlterField(
            model_name='variablehierarchy',
            name='subsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variablehierarchys', to='core.subsection'),
        ),
    ]
