# Generated by Django 4.0.3 on 2022-05-31 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_variablehierarchy_section_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variablehierarchy',
            unique_together={('name', 'section', 'subsection')},
        ),
    ]
