# Generated by Django 4.0.3 on 2022-05-31 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_variablehierarchy_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variablehierarchy',
            unique_together={('name', 'section', 'subsection')},
        ),
    ]
