# Generated by Django 4.0.3 on 2022-06-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_variablehierarchy_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablehierarchy',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
