# Generated by Django 4.0.3 on 2022-08-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_citation_page_from_alter_citation_page_to'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='citation',
            name='No_PAGE_FROM',
        ),
        migrations.RemoveConstraint(
            model_name='citation',
            name='No_PAGE_TO',
        ),
    ]
