# Generated by Django 4.0.3 on 2022-10-04 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_seshatcomment_seshatcommentpart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seshatcommentpart',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='seshatcommentpart',
            name='comment_citations',
        ),
        migrations.RemoveField(
            model_name='seshatcommentpart',
            name='comment_curator',
        ),
        migrations.DeleteModel(
            name='SeshatComment',
        ),
        migrations.DeleteModel(
            name='SeshatCommentPart',
        ),
    ]
