# Generated by Django 4.0.3 on 2022-10-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_seshatcomment_seshatcommentpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='seshatcommentpart',
            name='citation_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
