# Generated by Django 4.0.3 on 2022-11-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_ngapolityrel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngapolityrel',
            name='is_home_nga',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
