# Generated by Django 4.0.3 on 2022-11-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_polity_long_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='polity',
            name='new_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
