# Generated by Django 4.0.3 on 2022-11-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_capital_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='capital',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
