# Generated by Django 4.0.3 on 2023-01-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_nga_world_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ['-created_date', 'title']},
        ),
        migrations.AlterUniqueTogether(
            name='reference',
            unique_together={('zotero_link',)},
        ),
    ]
