# Generated by Django 4.0.3 on 2023-03-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_polity_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seshatcommentpart',
            options={'ordering': ['comment_order', 'modified_date']},
        ),
    ]
