# Generated by Django 4.0.3 on 2023-03-14 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_seshatcommentpart_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='polity',
            name='home_nga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_nga', to='core.nga'),
        ),
    ]
