# Generated by Django 4.0.3 on 2023-10-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_polity_polity_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='polity',
            name='general_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
