# Generated by Django 4.0.3 on 2023-10-19 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_polity_general_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nga',
            options={'ordering': ['name']},
        ),
    ]
