# Generated by Django 4.0.3 on 2023-12-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_polity_private_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Religion', max_length=100)),
                ('religion_name', models.CharField(blank=True, max_length=100, null=True)),
                ('religion_family', models.CharField(blank=True, max_length=100, null=True)),
                ('religion_genus', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
