# Generated by Django 4.0.3 on 2024-02-28 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_religion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seshatcommentpart',
            options={'ordering': ['modified_date']},
        ),
    ]
