manual_input_refs = [{'key': 'SADZ37NF',
  'itemType': 'book',
  'mainCreator': 'Kirch',
  'year': 2017,
  'title': 'On the Road of the Winds: An Archaeological History of the Pacific Islands before European Contact'},
 {'key': 'NZ5WCPT3',
  'itemType': 'book',
  'mainCreator': 'Rainbird',
  'year': 2004,
  'title': 'The Archaeology of Micronesia'},
 {'key': '5CBMW2DM',
  'itemType': 'book',
  'mainCreator': 'Amanat',
  'year': 2017,
  'title': 'Iran: A Modern History'},
 {'key': 'QU7TPGCN',
  'itemType': 'book',
  'mainCreator': 'Kodesh',
  'year': 2010,
  'title': 'Beyond the Royal Gaze: Clanship and Public Healing in Buganda'},
 {'key': 'P27ZMRHT',
  'itemType': 'journalArticle',
  'mainCreator': 'Mahdavi',
  'year': 2012,
  'title': 'Everyday Life in Late Qajar Iran.'},
 {'key': 'U8H846H8',
  'itemType': 'journalArticle',
  'mainCreator': 'Scarce',
  'year': 2007,
  'title': 'Entertainments East and West—Three Encounters between Iranians and Europeans during the Qajar Period (1786–1925)'},
 {'key': 'B6DA7U3R',
  'itemType': 'book',
  'mainCreator': 'Kamakau_et_al',
  'year': 1964,
  'title': "Ka Po'e Kahiko: The People of Old"},
 {'key': '5TFR8SHU',
  'itemType': 'book',
  'mainCreator': 'Kedit',
  'year': 1991,
  'title': 'Meanwhile, back home…BEJALAI and its effects on Iban men and women'},
 {'key': 'QXUQTP45',
  'itemType': 'book',
  'mainCreator': 'Heidhues',
  'year': 2000,
  'title': 'Southeast Asia: A Concise History'},
 {'key': '5P7FRWN5',
  'itemType': 'book',
  'mainCreator': 'Hall',
  'year': 1964,
  'title': 'A History of South-east Asia'},
 {'key': 'VHRMSMM3',
  'itemType': 'book',
  'mainCreator': 'Srivastava',
  'year': 2008,
  'title': 'History of Agriculture in India, Up to C. 1200 A.D.'},
 {'key': 'NTINK79N',
  'itemType': 'book',
  'mainCreator': 'Smith',
  'year': 2008,
  'title': 'The Cultural Foundations of Nations: Hierarchy, Covenant, and Republic'},
 {'key': 'F4J4UXGA',
  'itemType': 'book',
  'mainCreator': 'Grewal',
  'year': 2006,
  'title': 'The State and Society in Medieval India'},
 {'key': '7HBNNDG3',
  'itemType': 'book',
  'mainCreator': 'Young_Latham_Serjeant',
  'year': 1990,
  'title': "Religion, Learning and Science in the 'Abbasid Period"},
 {'key': 'EIN8PACR',
  'itemType': 'book',
  'mainCreator': 'Pálsson',
  'year': 1992,
  'title': 'Introduction: Text, life, and saga'},
 {'key': 'XE2HGNBF',
  'itemType': 'book',
  'mainCreator': 'Simon',
  'year': 2013,
  'title': 'Civil Society in China: The Legal Framework from Ancient Times to the "New Reform Era"'},
 {'key': 'UH8VJUC3',
  'itemType': 'book',
  'mainCreator': 'Lepage',
  'year': 2015,
  'title': 'Medieval Armies and Weapons in Western Europe: An Illustrated History'},
 {'key': 'N4MBEP49',
  'itemType': 'book',
  'mainCreator': 'Lepage',
  'year': 2015,
  'title': 'Medieval Armies and Weapons in Western Europe: An Illustrated History'},
 {'key': '2KQ4DFXR',
  'itemType': 'book',
  'mainCreator': 'Bergin',
  'year': 1985,
  'title': 'Cardinal Richelieu: Power and the Pursuit of Wealth'},
 {'key': 'D6JKQG6G',
  'itemType': 'book',
  'mainCreator': 'Bergin',
  'year': 1985,
  'title': 'Cardinal Richelieu: Power and the Pursuit of Wealth'},
 {'key': 'NFGBK5EH',
  'itemType': 'book',
  'mainCreator': 'Clark',
  'year': 1994,
  'title': 'Onions Are My Husband: Survival and Accumulation by West African Market Women'},
 {'key': 'J8RP7WWQ',
  'itemType': 'bookSection',
  'mainCreator': 'Schiller_Daniels_Bright',
  'year': 2006,
  'title': 'Khmer Writing'},
 {'key': 'DR37MMIT',
  'itemType': 'bookSection',
  'mainCreator': 'Mylonopoulos_Bonnechere_Gagné',
  'year': 2013,
  'title': 'Gory Details? The Iconography of Human Sacrifice in Greek Art (Plates II-IX)'},
 {'key': 'M2IXX5FS',
  'itemType': 'book',
  'mainCreator': 'Graham',
  'year': 1987,
  'title': 'Iban shamanism: an analysis of the ethnographic literature'},
 {'key': '4TF3WUNZ',
  'itemType': 'book',
  'mainCreator': 'antiquary',
  'year': 1824,
  'title': 'The History of Origins: Containing Ancient Historical Facts, with Singular Customs, Institutions, and Manners of Different Ages'},
 {'key': '7JSBK8C4',
  'itemType': 'book',
  'mainCreator': 'Southern',
  'year': 2011,
  'title': 'Ancient Rome The Republic 753BC-30BC'},
 {'key': '92CD5WKM',
  'itemType': 'book',
  'mainCreator': 'Zimmermann',
  'year': 1996,
  'title': 'The Law of Obligations: Roman Foundations of the Civilian Tradition'},
 {'key': 'BP2H4DJV',
  'itemType': 'book',
  'mainCreator': 'Potter_Hay',
  'year': 1975,
  'title': 'The New Cambridge Modern History, Vol. 1: The Renaissance, 1493-1520'},
 {'key': 'N6V92MHZ',
  'itemType': 'book',
  'mainCreator': 'Murray',
  'year': 2002,
  'title': 'Homosexualities'},
 {'key': 'VA73XSND',
  'itemType': 'book',
  'mainCreator': 'Alldritt',
  'year': 2009,
  'title': 'Buddhism'},
 {'key': 'BSJB3KQR',
  'itemType': 'book',
  'mainCreator': 'Ghosh',
  'year': 1990,
  'title': 'An Encyclopaedia of Indian Archaeology'},
 {'key': 'UZD2J8EG',
  'itemType': 'book',
  'mainCreator': 'Woolley',
  'year': 1965,
  'title': 'The Kassite period and the period of the Assyrian kings'},
 {'key': 'HRGFA2U3',
  'itemType': 'book',
  'mainCreator': 'Fuess_Hartung',
  'year': 2014,
  'title': 'Court Cultures in the Muslim World: Seventh to Nineteenth Centuries'},
 {'key': '5RHBEQ96',
  'itemType': 'book',
  'mainCreator': 'Beechert',
  'year': 1985,
  'title': 'Working in Hawaii: A Labor History'},
 {'key': 'RACSTH3W',
  'itemType': 'journalArticle',
  'mainCreator': 'Kornhuber_et_al',
  'year': 2023,
  'title': 'Risks of synchronized low yields are underestimated in climate and crop model projections'},
 {'key': 'P6EW2SYF',
  'itemType': 'webpage',
  'mainCreator': 'Foundation',
  'year': 0,
  'title': 'Welcome to Encyclopaedia Iranica'},
 {'key': 'INIKMV3C',
  'itemType': 'bookSection',
  'mainCreator': 'McCormick',
  'year': 0,
  'title': 'Emperors'},
 {'key': 'CQ7RN2E5',
  'itemType': 'book',
  'mainCreator': 'Cryer_Thomsen',
  'year': 2001,
  'title': 'Athlone History of Witchcraft and Magic in Europe: Biblical and Pagan Societies'},
 {'key': '2RJWIN6K',
  'itemType': 'bookSection',
  'mainCreator': 'Patton',
  'year': 2003,
  'title': 'Cosmic men and fluid exchanges: Myths of Arya, Varna and Jati in the Hindu tradition'},
 {'key': '9HPXJKXN',
  'itemType': 'bookSection',
  'mainCreator': 'Rutkowski',
  'year': 2007,
  'title': 'Problematyka militarna w Państwie Ur III'},
 {'key': 'QQWRHBPG',
  'itemType': 'encyclopediaArticle',
  'mainCreator': 'Malandra',
  'year': 2006,
  'title': 'VENDĪDĀD i. Survey of the history and contents of the text'},
 {'key': 'W4ER39F3',
  'itemType': 'webpage',
  'mainCreator': 'Foundation',
  'year': 0,
  'title': 'Welcome to Encyclopaedia Iranica'},
 {'key': 'S4Q6RRAG',
  'itemType': 'journalArticle',
  'mainCreator': 'Schmitt',
  'year': 1970,
  'title': 'Famine mortality in Hawaii'},
 {'key': 'AV4B546I',
  'itemType': 'journalArticle',
  'mainCreator': 'Harfst',
  'year': 1972,
  'title': 'Cause or Condition: Explanations of the Hawaiian Cultural Revolution'},
 {'key': 'RXKSN3FU',
  'itemType': 'journalArticle',
  'mainCreator': 'Stotzer',
  'year': 2014,
  'title': 'Sexual Orientation and/or Gender Identity/Expression Discrimination and Victimization among Self-Identified LGBTQI Native Hawaiians in Hawai‘i'},
 {'key': 'DNDWJFIK',
  'itemType': 'journalArticle',
  'mainCreator': 'Gonschor_Beamer',
  'year': 2014,
  'title': "Toward in Inventory of Ahupua'a in the Hawaiian Kingdom: A survey of Nineteenth- and early Twentieth-Century Cartographic and Archival Records of the Island of Hawai'i"},
 {'key': 'EUCXQXIP',
  'itemType': 'journalArticle',
  'mainCreator': 'MacGinnis',
  'year': 2011,
  'title': 'Neo-Babylonian Court Procedure. By Shalom E. Holtz. (Cuneiform Monographs 38). pp. 335. Leiden, Brill, 2009.'},
 {'key': 'US7KVUSG',
  'itemType': 'journalArticle',
  'mainCreator': 'van_Driel',
  'year': 1989,
  'title': 'The Murašûs in Context'},
 {'key': 'Z6MBJWJM',
  'itemType': 'journalArticle',
  'mainCreator': 'Foltz_Saadi-nejad',
  'year': 2007,
  'title': 'Is Zoroastrianism an Ecological Religion?'},
 {'key': 'ABIREAJG',
  'itemType': 'journalArticle',
  'mainCreator': 'Smith',
  'year': 1975,
  'title': 'Mongol Manpower and Persian Population'},
 {'key': 'K3DZ73WQ',
  'itemType': 'journalArticle',
  'mainCreator': 'Brown',
  'year': 1986,
  'title': 'Media and Secondary State Formation in the Neo-Assyrian Zagros: An Anthropological Approach to an Assyriological Problem'},
 {'key': 'GXEHKVZE',
  'itemType': 'journalArticle',
  'mainCreator': 'Mass',
  'year': 1983,
  'title': 'Patterns of Provincial Inheritance in Late Heian Japan'},
 {'key': 'SHIUNM3D',
  'itemType': 'journalArticle',
  'mainCreator': 'Tanigawa_谷川章雄',
  'year': 1992,
  'title': "Excavating Edo's Cemeteries: Graves as Indicators of Status and Class"},
 {'key': 'MDHWTWVN',
  'itemType': 'journalArticle',
  'mainCreator': 'Jordana_et_al',
  'year': 2009,
  'title': 'The warriors of the steppes: osteological evidence of warfare and violence from Pazyryk tumuli in the Mongolian Altai'},
 {'key': 'NM6MWQPB',
  'itemType': 'journalArticle',
  'mainCreator': 'Hallmann',
  'year': 2007,
  'title': 'The "Kushite Cloak" of Pekartror and Iriketakana: Novelty or Tradition?'},
 {'key': 'BKDQWQIU',
  'itemType': 'journalArticle',
  'mainCreator': 'Russmann',
  'year': 1995,
  'title': "Kushite Headdresses and 'Kushite' Style"},
 {'key': 'CVU3B5ZR',
  'itemType': 'journalArticle',
  'mainCreator': 'Farazmand',
  'year': 1998,
  'title': 'Administration of the Persian achaemenid world-state empire: implications for modern public administration'},
 {'key': '9E3NJ3EC',
  'itemType': 'journalArticle',
  'mainCreator': 'Hintze',
  'year': 2003,
  'title': 'Evil, Good, and Gender. Facets of the Feminine in Zoroastrian Religious History. BY Jamshed K. Choksy. pp. xii, 166. New York, Peter Lang, 2002.'},
 {'key': '8ZS2N3UX',
  'itemType': 'journalArticle',
  'mainCreator': 'Steinfeld',
  'year': 2015,
  'title': 'The Achaemenid Empire’s Contributions to Public Administration'},
 {'key': 'EQWHR4PF',
  'itemType': 'journalArticle',
  'mainCreator': 'Wieand',
  'year': 1917,
  'title': 'The Position of Women in the Late Roman Republic. Part I'},
 {'key': '6F3TRZHB',
  'itemType': 'journalArticle',
  'mainCreator': 'Frank',
  'year': 1930,
  'title': 'Roman Census Statistics from 508 to 225 B.C.'},
 {'key': 'N92XIVWE',
  'itemType': 'journalArticle',
  'mainCreator': 'Kawami',
  'year': 1982,
  'title': 'Parthian Brick Vaults in Mesopotamia, Their Antecedents and Descendants'},
 {'key': 'I3R65QGU',
  'itemType': 'book',
  'mainCreator': 'Martini',
  'year': 2017,
  'title': '‘Alā’ al-Dawla al-Simnānī Between Spiritual Authority and Political Power: A Persian Lord and Intellectual in the Heart of the Ilkhanate: With a Critical Edition of <i>al-Wārid al-šārid al-ṭārid šubhat al-mārid</i> and its Persian version <i>Zayn al-mu‘taqad li-zayn al-mu‘taqid</i>'},
 {'key': 'KBFW32QX',
  'itemType': 'book',
  'mainCreator': 'Gazerani',
  'year': 2015,
  'title': 'The Sistani Cycle of Epics and Iran’s National History: On the Margins of Historiography'},
 {'key': 'MRIPQZSR',
  'itemType': 'book',
  'mainCreator': 'Liebeschuetz',
  'year': 2015,
  'title': 'East and West in Late Antiquity: Invasion, Settlement, Ethnogenesis and Conflicts of Religion'},
 {'key': '35B5KRG4',
  'itemType': 'book',
  'mainCreator': 'Ascheri',
  'year': 2013,
  'title': 'The Laws of Late Medieval Italy (1000-1500): Foundations for a European Legal System'},
 {'key': '53T4RR8W',
  'itemType': 'bookSection',
  'mainCreator': 'Aron-Beller',
  'year': 2019,
  'title': 'Ghettoization: The Papal Enclosure and Its Jews'},
 {'key': 'EXZP5W4C',
  'itemType': 'bookSection',
  'mainCreator': 'Verboven_Laes',
  'year': 2017,
  'title': '1 Work, Labour, Professions. What’s in a Name?'},
 {'key': 'B6FR7R6W',
  'itemType': 'bookSection',
  'mainCreator': 'Verboven_et_al',
  'year': 2016,
  'title': 'Work, Labour, and Professions in the Roman World'},
 {'key': 'RADBF5MG',
  'itemType': 'bookSection',
  'mainCreator': 'Barkmann',
  'year': 2000,
  'title': 'Some Comments on the Consequences of the Decline of the Mongol Empire on the Social Development of the Mongols'},
 {'key': '6IMBN45P',
  'itemType': 'bookSection',
  'mainCreator': 'Jaspert',
  'year': 2015,
  'title': 'An Introduction to Discourses of Purity in Transcultural Perspective'},
 {'key': 'XZSBR6GP',
  'itemType': 'bookSection',
  'mainCreator': 'Bareket',
  'year': 1997,
  'title': 'Personal Adversities of Jews during the Period of the Fatimid Wars in Eleventh Century Palestine'},
 {'key': 'N6NAFBTE',
  'itemType': 'bookSection',
  'mainCreator': 'Lev_et_al',
  'year': 2022,
  'title': 'War and Society in the Eastern Mediterranean, 7th-15th Centuries'},
 {'key': 'ZQUQNPTT',
  'itemType': 'book',
  'mainCreator': 'Keyvanian',
  'year': 2015,
  'title': 'Hospitals and Urbanism in Rome, 1200-1500'},
 {'key': 'TFKVDB6K',
  'itemType': 'bookSection',
  'mainCreator': 'Hunter',
  'year': 2013,
  'title': 'Kālidāsa’s Raghuvaṃśa and the Kakawin Sumanasāntaka'},
 {'key': 'GB8ZSN46',
  'itemType': 'bookSection',
  'mainCreator': 'Worsley_et_al',
  'year': 2013,
  'title': 'Front Matter'},
 {'key': 'RX344CWS',
  'itemType': 'book',
  'mainCreator': 'Soekmono',
  'year': 1995,
  'title': 'The Javanese Candi: Function and Meaning'},
 {'key': 'NA8R37PZ',
  'itemType': 'bookSection',
  'mainCreator': 'Christie',
  'year': 2015,
  'title': 'Under the Volcano: Stabilizing the Early Javanese State in an Unstable Environment'},
 {'key': 'QAAEMM5E',
  'itemType': 'bookSection',
  'mainCreator': 'Speziale',
  'year': 2012,
  'title': 'Introduction'},
 {'key': '4B7NXWWV',
  'itemType': 'bookSection',
  'mainCreator': 'Berkel',
  'year': 2013,
  'title': '4. The Bureaucracy'},
 {'key': 'EN95BA47',
  'itemType': 'bookSection',
  'mainCreator': 'Cheikh',
  'year': 2013,
  'title': '7. The Harem'},
 {'key': '5TFWG76K',
  'itemType': 'bookSection',
  'mainCreator': 'Radner',
  'year': 2003,
  'title': 'MESOPOTAMIA: NEO-ASSYRIAN PERIOD'},
 {'key': 'V8IJ38KI',
  'itemType': 'book',
  'mainCreator': 'Boyce',
  'year': 2015,
  'title': 'A History of Zoroastrianism, Zoroastrianism under the Achaemenians'},
 {'key': 'D4CAAFAH',
  'itemType': 'book',
  'mainCreator': 'Lewis',
  'year': 1977,
  'title': 'Sparta and Persia: Lectures Delivered at the University of Cincinnati, Autumn 1976, in Memory of Donald W. Bradeen'},
 {'key': 'UFQ4NAXK',
  'itemType': 'book',
  'mainCreator': 'Stewart',
  'year': 2021,
  'title': "The Armenian Kingdom and the Mamluks: War and Diplomacy during the Reigns of Het'um II (1289-1307)"},
 {'key': '8DV9Z6JE',
  'itemType': 'journalArticle',
  'mainCreator': 'Berlekamp',
  'year': 2010,
  'title': "The Limits of Artistic Exchange in Fourteenth-Century Tabriz: The Paradox of Rashid Al-Din's Book on Chinese Medicine, Part I"},
 {'key': 'Q7NPGAMJ',
  'itemType': 'bookSection',
  'mainCreator': 'Nylan',
  'year': 2009,
  'title': 'Classics Without Canonization: Learning And Authority In Qin And Han'},
 {'key': 'ZBEQMJB5',
  'itemType': 'bookSection',
  'mainCreator': 'Jianmin',
  'year': 2009,
  'title': 'They Shall Expel Demons: Etiology, The Medical Canon And The Transformation Of Medical Techniques Before The Tang'},
 {'key': 'X4XDSEMQ',
  'itemType': 'bookSection',
  'mainCreator': 'Tseng-Kuei',
  'year': 2009,
  'title': 'Taboos: An Aspect Of Belief In The Qin And Han'},
 {'key': 'W5MQXECV',
  'itemType': 'book',
  'mainCreator': 'Sato',
  'year': 2021,
  'title': 'The Confucian Quest for Order: The Origin and Formation of the Political Thought of Xun Zi'},
 {'key': 'GRNKMFHV',
  'itemType': 'bookSection',
  'mainCreator': 'Retsö',
  'year': 2005,
  'title': 'Arabia and the Heritage of the Axial Age'},
 {'key': 'AZV8ZR7G',
  'itemType': 'bookSection',
  'mainCreator': 'Scheid_Peachin',
  'year': 2011,
  'title': 'Graeco-Roman Cultic Societies'},
 {'key': '4H7K3NHS',
  'itemType': 'book',
  'mainCreator': 'Neusner',
  'year': 2022,
  'title': 'A History of the Jews in Babylonia, Part 5. Later Sasanian Times'},
 {'key': '5AI436TM',
  'itemType': 'book',
  'mainCreator': 'Boyce_Grenet',
  'year': 2015,
  'title': 'A History of Zoroastrianism, Zoroastrianism under Macedonian and Roman Rule'},
 {'key': 'AJPN68DT',
  'itemType': 'journalArticle',
  'mainCreator': 'Fay',
  'year': 1997,
  'title': "Women and Waqf: Toward a Reconsideration of Women's Place in the Mamluk Household"},
 {'key': 'MHZWAKP3',
  'itemType': 'book',
  'mainCreator': 'Raphael',
  'year': 2013,
  'title': 'Climate and Political Climate: Environmental Disasters in the Medieval Levant'},
 {'key': 'SHFKCNMR',
  'itemType': 'bookSection',
  'mainCreator': 'Staffa',
  'year': 2021,
  'title': 'Conquest and Fusion: The Social Evolution of Cairo A.D. 642-1850'},
 {'key': 'U53NHMFU',
  'itemType': 'journalArticle',
  'mainCreator': 'Grossmann_et_al',
  'year': 2023,
  'title': 'AI and the transformation of social science research'},
 {'key': 'MHU4TH5H',
  'itemType': 'journalArticle',
  'mainCreator': 'Hunger',
  'year': 1982,
  'title': 'State and Society in Byzantium'},
 {'key': '97V3AA68',
  'itemType': 'book',
  'mainCreator': 'Thomas_Mallett',
  'year': 2010,
  'title': 'Christian-Muslim Relations. A Bibliographical History. Volume 2 (900-1050)'},
 {'key': '2P9AXB7A',
  'itemType': 'book',
  'mainCreator': 'Bourbou',
  'year': 2016,
  'title': 'Health and Disease in Byzantine Crete (7th–12th centuries AD)'},
 {'key': 'B8ZUI7V3',
  'itemType': 'journalArticle',
  'mainCreator': 'Whitehouse',
  'year': 2023,
  'title': 'Ritual, community, and conflict: reflections on the science of the social and its practical implications'},
 {'key': 'TJNNSFQQ',
  'itemType': 'book',
  'mainCreator': 'Stokes',
  'year': 2009,
  'title': 'Encyclopedia of the Peoples of Africa and the Middle East'},
 {'key': 'Q4D2UVNZ',
  'itemType': 'book',
  'mainCreator': 'Garland',
  'year': 2002,
  'title': 'Byzantine Empresses: Women and Power in Byzantium AD 527-1204'},
 {'key': 'HEMNCXZC',
  'itemType': 'book',
  'mainCreator': 'Rostovtzeff',
  'year': 1941,
  'title': 'The Social & Economic History of the Hellenistic World'},
 {'key': '72GW3AHW',
  'itemType': 'book',
  'mainCreator': 'Pathak',
  'year': 1995,
  'title': 'Concept of maintenace in Garo customary law'},
 {'key': 'PWXVU49E',
  'itemType': 'journalArticle',
  'mainCreator': 'Goswami_Majumdar',
  'year': 1965,
  'title': "A Study of women's position among the Garo"},
 {'key': 'IPG2CQKD',
  'itemType': 'book',
  'mainCreator': 'Nketia',
  'year': 1969,
  'title': 'Funeral dirges of the Akan people'},
 {'key': 'SSXB4GND',
  'itemType': 'journalArticle',
  'mainCreator': 'Swartz',
  'year': 1958,
  'title': 'Sexuality and aggression on Romonum, Truk'},
 {'key': 'QSQMSQZ2',
  'itemType': 'journalArticle',
  'mainCreator': 'Swartz',
  'year': 1965,
  'title': 'Personality and structure: political acquiesence in Truk'},
 {'key': 'U4AI6FDU',
  'itemType': 'journalArticle',
  'mainCreator': 'Goodenough',
  'year': 1949,
  'title': 'Premarital freedom on Truk: theory and practice'},
 {'key': '57IZX7SE',
  'itemType': 'journalArticle',
  'mainCreator': 'Mahony',
  'year': 1960,
  'title': 'Taro cultivation in Truk'},
 {'key': 'TF44PFCM',
  'itemType': 'journalArticle',
  'mainCreator': 'Marshall_Marshall',
  'year': 1982,
  'title': 'Education of women and family size in two Micronesian communities'},
 {'key': 'T3RX2JK3',
  'itemType': 'journalArticle',
  'mainCreator': 'Marshall_Marshall',
  'year': 1984,
  'title': 'Infant feeding practices in a Trukese village'},
 {'key': 'B395STWA',
  'itemType': 'book',
  'mainCreator': 'Garstang',
  'year': 1953,
  'title': 'Prehistoric Mersin, Yümük Tepe in Southern Turkey: The Neilson Expedition in Cilicia'},
 {'key': 'GXDIESBW',
  'itemType': 'thesis',
  'mainCreator': 'Eren',
  'year': 2010,
  'title': 'An Application of Depth Analysis on Middle Bronze Agce Palaces at Açemhöyük, Tell Mardikh and Kültepe'},
 {'key': 'QC4QCQPC',
  'itemType': 'journalArticle',
  'mainCreator': 'French',
  'year': 1962,
  'title': 'Excavations at Can Hasan, Second Preliminary Report'},
 {'key': 'RCRRXBZC',
  'itemType': 'book',
  'mainCreator': 'Christie',
  'year': 2006,
  'title': 'From Constantine to Charlemagne: An Archaeology of Italy, AD 300-800'},
 {'key': 'CI2RWI34',
  'itemType': 'book',
  'mainCreator': 'BITTEL',
  'year': 1970,
  'title': 'HATTUSHA THE CAPITAL OF THE HITTITES'},
 {'key': 'RI8NP28I',
  'itemType': 'book',
  'mainCreator': 'BITTEL',
  'year': 1970,
  'title': 'HATTUSHA THE CAPITAL OF THE HITTITES'},
 {'key': '9CR2575N',
  'itemType': 'book',
  'mainCreator': 'Greenewalt_Payne',
  'year': 1978,
  'title': 'Ritual Dinners in Early Historic Sardis'},
 {'key': 'VX8VJA3Q',
  'itemType': 'journalArticle',
  'mainCreator': 'Nakamura_Meskell',
  'year': 2009,
  'title': 'Articulate Bodies: Forms and Figures at Çatalhöyük'},
 {'key': 'P9FHW3KT',
  'itemType': 'book',
  'mainCreator': 'Wasserstein_Ayalon',
  'year': 2013,
  'title': 'Mamluks and Ottomans: Studies in Honour of Michael Winter'},
 {'key': '57CWQVQP',
  'itemType': 'book',
  'mainCreator': 'Somel',
  'year': 2010,
  'title': 'The A to Z of the Ottoman Empire'},
 {'key': 'NT4E8J68',
  'itemType': 'bookSection',
  'mainCreator': 'Geldof',
  'year': 2015,
  'title': '2 “And to describe the shapes of the dead”: Making Sense of the Archaeology of Armed Violence'},
 {'key': 'Z9BVSD3Q',
  'itemType': 'book',
  'mainCreator': 'Cohen',
  'year': 2005,
  'title': "Death rituals, ideology, and the development of early Mesopotamian kingship: towards a new understanding of Iraq's royal cemetery of Ur"},
 {'key': 'N2HZX9XK',
  'itemType': 'bookSection',
  'mainCreator': 'Yoffee_Emberling',
  'year': 2015,
  'title': 'Mesopotamian cities and urban process, 3500–1600BCE'},
 {'key': 'NPWEUJHK',
  'itemType': 'book',
  'mainCreator': 'Rappa',
  'year': 2017,
  'title': 'The King and the Making of Modern Thailand'},
 {'key': 'B4PRNTR2',
  'itemType': 'book',
  'mainCreator': 'Salkin_Boda',
  'year': 1995,
  'title': 'International Dictionary of Historic Places: Southern Europe'},
 {'key': 'K2FIXND6',
  'itemType': 'book',
  'mainCreator': 'Leadbetter',
  'year': 2009,
  'title': 'Galerius and the Will of Diocletian'},
 {'key': 'GT2B3XXJ',
  'itemType': 'book',
  'mainCreator': 'Society_for_the_Diffusion_of_Useful_Knowledge_(Great_Britain)_Britain)',
  'year': 1833,
  'title': 'Penny Cyclopaedia of the Society for the Diffusion of Useful Knowledge'},
 {'key': 'I67UD5MG',
  'itemType': 'bookSection',
  'mainCreator': 'Devisse',
  'year': 1988,
  'title': 'Trade and trade routes in West Africa'},
 {'key': 'YXIN4SM3',
  'itemType': 'book',
  'mainCreator': 'Hutton',
  'year': 1926,
  'title': 'The Story of Ravenna'},
 {'key': 'YKXVEHAF',
  'itemType': 'book',
  'mainCreator': 'Crawford',
  'year': 1996,
  'title': 'Roman Statutes'},
 {'key': '2AWPF4SF',
  'itemType': 'bookSection',
  'mainCreator': 'Kosiba',
  'year': 2011,
  'title': 'The Politics of Locality: Pre-Inka social landscapes in the Cusco region, Peru'},
 {'key': 'EHBCRWX7',
  'itemType': 'journalArticle',
  'mainCreator': 'Chittick',
  'year': 2010,
  'title': "Competitive Spectacle during China's Northern and Southern Dynasties: With\nParticular Emphasis on Dragon Boat Racing"},
 {'key': '7U439VPE',
  'itemType': 'webpage',
  'mainCreator': 'NO_CREATOR',
  'year': 0,
  'title': 'Babylonian mathematics'},
 {'key': 'TMKXHM4E',
  'itemType': 'book',
  'mainCreator': 'Marcellinus',
  'year': 1939,
  'title': 'History, Books 29 Excerpta Valesiana'},
 {'key': '5Y2Y2C6D',
  'itemType': 'bookSection',
  'mainCreator': 'Yoffee_Stark',
  'year': 2015,
  'title': 'Southeast Asian urbanism: from early city to Classical state'},
 {'key': 'EM55R3V8',
  'itemType': 'book',
  'mainCreator': 'Young_University_of_California_Libraries',
  'year': 1900,
  'title': 'The kingdom of the yellow robe; being sketches of the domestic and religious rites and ceremonies of the Siamese'},
 {'key': 'QPM6EBW9',
  'itemType': 'book',
  'mainCreator': 'Glick_Livesey_Wallis',
  'year': 2014,
  'title': 'Medieval Science, Technology, and Medicine: An Encyclopedia'},
 {'key': 'B2ANEI67',
  'itemType': 'book',
  'mainCreator': 'Shafer_et_al',
  'year': 2005,
  'title': 'Temples of ancient Egypt'},
 {'key': 'SFMNQWCT',
  'itemType': 'journalArticle',
  'mainCreator': 'Christie',
  'year': 1996,
  'title': 'Money and its Uses in the Javanese States of the Ninth to Fifteenth Centuries A.D.'},
 {'key': 'AE9JC2GQ',
  'itemType': 'book',
  'mainCreator': 'Davis',
  'year': 1913,
  'title': 'Readings in ancient history: Illustrative extracts from the sources'},
 {'key': 'FBJBCKMT',
  'itemType': 'bookSection',
  'mainCreator': 'Sneath',
  'year': 2010,
  'title': 'Introduction'},
 {'key': 'E6W9DBZT',
  'itemType': 'book',
  'mainCreator': 'Joannes',
  'year': 2007,
  'title': 'Historia Mezopotamii w 1. tysiącleciu przed Chrystusem'},
 {'key': '5ITXJIXA',
  'itemType': 'book',
  'mainCreator': 'Rainey',
  'year': 2010,
  'title': 'Confucius and Confucianism: The Essentials'},
 {'key': 'EJRCBIXQ',
  'itemType': 'book',
  'mainCreator': 'Creese',
  'year': 2004,
  'title': 'Women of the Kakawin World: Marriage and Sexuality in the Indic Courts of Java and Bali'},
 {'key': '4RJC7GV2',
  'itemType': 'book',
  'mainCreator': 'Barmé',
  'year': 2011,
  'title': 'The Forbidden City'},
 {'key': '3PM6RAQR',
  'itemType': 'book',
  'mainCreator': 'Haldon',
  'year': 2005,
  'title': 'The Palgrave Atlas of Byzantine History'},
 {'key': 'W6DMZ5QS',
  'itemType': 'book',
  'mainCreator': 'Johnston',
  'year': 2011,
  'title': 'Twilight in the Forbidden City'},
 {'key': 'KBJ6I7IX',
  'itemType': 'bookSection',
  'mainCreator': 'Shaughnessy_Loewe_Rawson',
  'year': 1999,
  'title': 'Western Zhou Archaeology'},
 {'key': 'NZGPJ7ZA',
  'itemType': 'book',
  'mainCreator': 'Hen',
  'year': 1995,
  'title': 'Culture and Religion in Merovingian Gaul: A.D. 481-751'},
 {'key': 'HBPSWC6C',
  'itemType': 'book',
  'mainCreator': 'Parthasarathi',
  'year': 2011,
  'title': 'Why Europe Grew Rich and Asia Did Not: Global Economic Divergence, 1600–1850'},
 {'key': '89DFW4AN',
  'itemType': 'bookSection',
  'mainCreator': 'Shepard_Kaegi',
  'year': 2019,
  'title': 'Confronting Islam: Emperors Versus Caliphs (641–c.850)'},
 {'key': 'NB9MH3T9',
  'itemType': 'book',
  'mainCreator': 'Brubaker_Smith',
  'year': 2004,
  'title': 'Gender in the Early Medieval World: East and West, 300-900'},
 {'key': 'VC8W8EEZ',
  'itemType': 'bookSection',
  'mainCreator': 'Petry_Kennedy',
  'year': 1998,
  'title': 'Egypt as a province in the Islamic caliphate, 641–868'},
 {'key': 'H453IWJ9',
  'itemType': 'book',
  'mainCreator': 'Dusinberre',
  'year': 2003,
  'title': 'Aspects of Empire in Achaemenid Sardis'},
 {'key': '6J3AWTHP',
  'itemType': 'bookSection',
  'mainCreator': 'Fleet_Crane',
  'year': 2009,
  'title': 'Art and architecture, 1300–1453'},
 {'key': 'W9MWQSEH',
  'itemType': 'bookSection',
  'mainCreator': 'Oliver_Levtzion',
  'year': 1977,
  'title': 'The western Maghrib and Sudan'},
 {'key': 'JGU62A8K',
  'itemType': 'bookSection',
  'mainCreator': 'Twitchett_et_al',
  'year': 1994,
  'title': 'The Liao'},
 {'key': 'MP4DNBJI',
  'itemType': 'book',
  'mainCreator': 'Campbell',
  'year': 2018,
  'title': 'Violence, Kinship and the Early Chinese State: The Shang and their World'},
 {'key': 'WQF53PAJ',
  'itemType': 'book',
  'mainCreator': 'Despeux',
  'year': 2000,
  'title': 'Women in Daoism'},
 {'key': 'G2MR7G4R',
  'itemType': 'bookSection',
  'mainCreator': 'Twitchett_Loewe_Bielenstein',
  'year': 1986,
  'title': 'The institutions of Later Han'},
 {'key': 'IFUR84QD',
  'itemType': 'bookSection',
  'mainCreator': 'Fleet_Chrysostomides',
  'year': 2009,
  'title': 'The Byzantine Empire from the eleventh to the fifteenth century'},
 {'key': 'D8IE2XAD',
  'itemType': 'bookSection',
  'mainCreator': 'Jamsran_Sneath',
  'year': 2010,
  'title': 'The Crisis of the Forty and the Four'},
 {'key': 'MGHTH44W',
  'itemType': 'journalArticle',
  'mainCreator': 'Tumurtogoo',
  'year': 2014,
  'title': 'The Formation of the Oirat Dialect'},
 {'key': '5QZUCJMA',
  'itemType': 'book',
  'mainCreator': 'Kuhrt',
  'year': 2013,
  'title': 'The Persian Empire: A Corpus of Sources from the Achaemenid Period'},
 {'key': 'HRUB2EG3',
  'itemType': 'book',
  'mainCreator': 'Warren',
  'year': 1975,
  'title': 'The Techiman-Bono of Ghana: an ethnography of an Akan society'},
 {'key': '9RIPSCB4',
  'itemType': 'journalArticle',
  'mainCreator': 'Blackburn',
  'year': 1985,
  'title': 'Death and Deification: Folk Cults in Hinduism'},
 {'key': '59B7ZM3N',
  'itemType': 'book',
  'mainCreator': 'Martin',
  'year': 2005,
  'title': 'The Qajar pact: bargaining, protest and the state in nineteenth-century Persia'},
 {'key': '6Z2W4TIC',
  'itemType': 'book',
  'mainCreator': 'Deng',
  'year': 2010,
  'title': 'State And Civil Society: The Chinese Perspective'},
 {'key': 'MINEF7X8',
  'itemType': 'book',
  'mainCreator': 'Deng',
  'year': 2002,
  'title': 'The Premodern Chinese Economy: Structural Equilibrium and Capitalist Sterility'},
 {'key': 'C2K9T7WH',
  'itemType': 'journalArticle',
  'mainCreator': 'Nelson',
  'year': 2004,
  'title': 'Slavery in Medieval Japan'},
 {'key': '9JH7BNW9',
  'itemType': 'journalArticle',
  'mainCreator': 'Wall_Musgrave_Warren',
  'year': 1986,
  'title': 'Human Bones from a Late Minoan IB House at Knossos'},
 {'key': 'VHIIZATE',
  'itemType': 'book',
  'mainCreator': 'Ghani_Ghanī',
  'year': 2000,
  'title': 'Iran and the rise of Reza Shah: From Qajar collapse to Pahlavi power'},
 {'key': 'N8D8E8HW',
  'itemType': 'book',
  'mainCreator': 'Jones',
  'year': 2012,
  'title': 'The Military History Book: The Ultimate Visual Guide to the Weapons that Shaped the World'},
 {'key': 'SZ286Q33',
  'itemType': 'book',
  'mainCreator': 'Chaniotis',
  'year': 2005,
  'title': 'War in the Hellenistic World: A Social and Cultural History'},
 {'key': '58FN3WWW',
  'itemType': 'book',
  'mainCreator': 'Lorge',
  'year': 2006,
  'title': 'War, Politics and Society in Early Modern China, 900–1795'},
 {'key': 'M7X6GJV5',
  'itemType': 'bookSection',
  'mainCreator': 'Lawrence_et_al',
  'year': 2013,
  'title': 'Muslim Engagement with Injustice and Violence'},
 {'key': 'MH7EG2TM',
  'itemType': 'book',
  'mainCreator': 'Schneider',
  'year': 1996,
  'title': 'The Ceremonial City: Toulouse Observed, 1738-1780'},
 {'key': 'S5QPZGSK',
  'itemType': 'journalArticle',
  'mainCreator': 'Shapland',
  'year': 0,
  'title': 'The Minoan lion: presence and absence on Bronze Age Crete'},
 {'key': 'E4F6XBGF',
  'itemType': 'journalArticle',
  'mainCreator': 'Mathur',
  'year': 2007,
  'title': 'Medieval Hindu Law: A Study of Post-Smṛti Changes in Hindu Law'},
 {'key': '643STRJ7',
  'itemType': 'book',
  'mainCreator': 'Shahar_Weller',
  'year': 1996,
  'title': 'Unruly Gods: Divinity and Society in China'},
 {'key': '4I62M5EP',
  'itemType': 'book',
  'mainCreator': 'Peregrine_Ember',
  'year': 2001,
  'title': 'Encyclopedia of Prehistory: Volume 3: East Asia and Oceania'},
 {'key': 'XSPADN9U',
  'itemType': 'book',
  'mainCreator': 'Shahar_Weller',
  'year': 1996,
  'title': 'Unruly Gods: Divinity and Society in China'},
 {'key': '5W756777',
  'itemType': 'document',
  'mainCreator': 'Eder',
  'year': 1970,
  'title': '庚申信仰 [Belief in Koshin]'},
 {'key': 'QA7K5U2V',
  'itemType': 'book',
  'mainCreator': 'Curtis_Stewart',
  'year': 2007,
  'title': 'The Age of the Parthians'},
 {'key': 'VD43E52J',
  'itemType': 'encyclopediaArticle',
  'mainCreator': 'Sundelin_Shillington',
  'year': 2005,
  'title': 'Encyclopedia of African History'},
 {'key': 'X7Q4JJFC',
  'itemType': 'encyclopediaArticle',
  'mainCreator': 'Papadakis',
  'year': 1991,
  'title': 'Excommunication'},
 {'key': 'U8PMEDQW',
  'itemType': 'encyclopediaArticle',
  'mainCreator': 'Dandamayev',
  'year': 1988,
  'title': 'BARDA and BARDA-DĀRI i. Achaemenid Period'},
 {'key': 'EAPQC2JW',
  'itemType': 'book',
  'mainCreator': 'Woods',
  'year': 1976,
  'title': 'The Aqquyunlu'},
 {'key': 'CCIITMHP',
  'itemType': 'blogPost',
  'mainCreator': 'Rezakhani',
  'year': 0,
  'title': 'ARSACID SOCIETY AND CULTURE'},
 {'key': 'DM9A788V',
  'itemType': 'book',
  'mainCreator': 'de_Jong',
  'year': 2017,
  'title': 'The Archaeology of Death in Roman Syria: Burial, Commemoration, and Empire'},
 {'key': 'I5CDS8PW',
  'itemType': 'bookSection',
  'mainCreator': 'Melville_et_al',
  'year': 1991,
  'title': 'RELIGIOUS FORCES IN EIGHTEENTH- AND NINETEENTH-CENTURY IRAN'},
 {'key': 'NGATJVAP',
  'itemType': 'book',
  'mainCreator': 'Ateş',
  'year': 2013,
  'title': 'Ottoman-Iranian Borderlands: Making a Boundary, 1843–1914'},
 {'key': 'BRGPBZUS',
  'itemType': 'book',
  'mainCreator': 'Arnold',
  'year': 2014,
  'title': 'Theoderic and the Roman Imperial Restoration'},
 {'key': 'U8KMNTEF',
  'itemType': 'book',
  'mainCreator': 'Cavallo',
  'year': 1995,
  'title': 'Charity and Power in Early Modern Italy: Benefactors and Their Motives in Turin, 1541-1789'},
 {'key': 'T3DNQPQK',
  'itemType': 'bookSection',
  'mainCreator': 'Morris_et_al',
  'year': 2007,
  'title': 'Demography'},
 {'key': 'MVWESX6Z',
  'itemType': 'bookSection',
  'mainCreator': 'Morris_et_al',
  'year': 2007,
  'title': 'Ecology'},
 {'key': '2UKEM46X',
  'itemType': 'book',
  'mainCreator': 'Burroughs',
  'year': 1990,
  'title': 'From Signs to Design: Environmental Process and Reform in Early Renaissance Rome'},
 {'key': 'KFBT2XUD',
  'itemType': 'book',
  'mainCreator': 'Grierson_Blackburn',
  'year': 2007,
  'title': 'Medieval European Coinage: Volume 1, The Early Middle Ages (5th-10th Centuries)'},
 {'key': 'NNTDQC2K',
  'itemType': 'bookSection',
  'mainCreator': 'Atkins_Osborne_Parkin',
  'year': 2006,
  'title': '‘You do him no service’: an exploration of pagan almsgiving'},
 {'key': 'S4GVEQI4',
  'itemType': 'book',
  'mainCreator': 'Riddle',
  'year': 1997,
  'title': 'Eve’s Herbs: A History of Contraception and Abortion in the West'},
 {'key': 'ZTDQUHCE',
  'itemType': 'book',
  'mainCreator': 'Souza',
  'year': 2002,
  'title': 'Piracy in the Graeco-Roman World'},
 {'key': 'F95FZW9Q',
  'itemType': 'bookSection',
  'mainCreator': 'Gill_et_al',
  'year': 2016,
  'title': 'Evidence for injuries and violent death'},
 {'key': 'I42FGK6G',
  'itemType': 'bookSection',
  'mainCreator': 'Jolly_Macintyre_Ralston',
  'year': 1989,
  'title': 'Changes in the lives of ordinary women in early post-contact Hawaii'},
 {'key': '7DXB7I5M',
  'itemType': 'book',
  'mainCreator': 'Lewis',
  'year': 2009,
  'title': 'China Between Empires: The Northern and Southern Dynasties'},
 {'key': '2DR6EN6R',
  'itemType': 'book',
  'mainCreator': 'Folda',
  'year': 2005,
  'title': 'Crusader Art in the Holy Land, From the Third Crusade to the Fall of Acre'},
 {'key': 'KT4RBHFU',
  'itemType': 'bookSection',
  'mainCreator': 'Quintana',
  'year': 2011,
  'title': 'Elamitas Frente a Persas: el Reino Independiente de Ansan'},
 {'key': 'MASZPSIX',
  'itemType': 'bookSection',
  'mainCreator': 'Shelmerdine_Shelmerdine',
  'year': 2008,
  'title': 'Background, Sources, and Methods'},
 {'key': 'AF6SDPA9',
  'itemType': 'book',
  'mainCreator': 'Holo',
  'year': 2009,
  'title': 'Byzantine Jewry in the Mediterranean Economy'},
 {'key': 'FNP45QKF',
  'itemType': 'book',
  'mainCreator': 'Kaegi',
  'year': 2003,
  'title': 'Heraclius, Emperor of Byzantium'},
 {'key': 'QC3UTF4W',
  'itemType': 'bookSection',
  'mainCreator': 'Lange_Songul_Tor',
  'year': 2011,
  'title': '‘SOVEREIGN AND PIOUS’: THE RELIGIOUS LIFE OF THE GREAT SELJUQ SULTANS'},
 {'key': 'MWXG6628',
  'itemType': 'bookSection',
  'mainCreator': 'Gadd_et_al',
  'year': 1971,
  'title': 'PERSIA, c. 2400–1800 B.C.'},
 {'key': 'KRIXZK43',
  'itemType': 'bookSection',
  'mainCreator': 'Gadd_et_al',
  'year': 1973,
  'title': 'PERSIA c. 1800–1550 B.C.'},
 {'key': 'MK4ZSH2G',
  'itemType': 'book',
  'mainCreator': 'Harper',
  'year': 2011,
  'title': 'Slavery in the Late Roman World, AD 275–425'},
 {'key': 'Z5BGADN7',
  'itemType': 'book',
  'mainCreator': 'Amory',
  'year': 1997,
  'title': 'People and Identity in Ostrogothic Italy, 489–554'},
 {'key': '4TPAK3MQ',
  'itemType': 'bookSection',
  'mainCreator': 'Ephrat',
  'year': 2012,
  'title': 'The Seljuqs and the public sphere in the period of Sunni revivalism: The view from Baghdad'},
 {'key': 'KJWGMI4Q',
  'itemType': 'book',
  'mainCreator': 'Dean',
  'year': 1987,
  'title': 'Land and Power in Late Medieval Ferrara: The Rule of the Este, 1350-1450'},
 {'key': '76695I56',
  'itemType': 'bookSection',
  'mainCreator': 'Flower_Culham',
  'year': 2014,
  'title': 'Women in the Roman Republic'},
 {'key': 'AVZ4HZEM',
  'itemType': 'bookSection',
  'mainCreator': 'Lintott_et_al',
  'year': 1994,
  'title': 'The Roman empire and its problems in the late second century'},
 {'key': 'VI66JVI3',
  'itemType': 'bookSection',
  'mainCreator': 'Lintott_et_al',
  'year': 1994,
  'title': 'Mithridates'},
 {'key': 'MAQE9ZW6',
  'itemType': 'bookSection',
  'mainCreator': 'Lintott_et_al',
  'year': 1994,
  'title': 'Sulla'},
 {'key': 'WE3ZAUN8',
  'itemType': 'bookSection',
  'mainCreator': 'Lintott_et_al',
  'year': 1994,
  'title': 'Lucullus, Pompey and the East'},
 {'key': 'K9XPI26T',
  'itemType': 'book',
  'mainCreator': 'Kolata',
  'year': 2013,
  'title': 'Ancient Inca'},
 {'key': 'DNSWRA2F',
  'itemType': 'book',
  'mainCreator': 'Harries',
  'year': 2007,
  'title': 'Law and Crime in the Roman World'},
 {'key': 'VJA63E9G',
  'itemType': 'bookSection',
  'mainCreator': 'Dresser',
  'year': 2015,
  'title': 'JAPAN ITS ARCHITECTURE, ART, AND ART MANUFACTURES'},
 {'key': '6KS99HFK',
  'itemType': 'bookSection',
  'mainCreator': 'Cameron_Garnsey_Blockley',
  'year': 1997,
  'title': 'The dynasty of Theodosius'},
 {'key': 'HKRTUMSH',
  'itemType': 'bookSection',
  'mainCreator': 'Cameron_et_al',
  'year': 2001,
  'title': 'The western empire, 425–76'},
 {'key': '3RC2HS5C',
  'itemType': 'book',
  'mainCreator': 'Tamaki',
  'year': 1995,
  'title': 'Japanese Banking: A History, 1859-1959'},
 {'key': 'UPFU23X9',
  'itemType': 'journalArticle',
  'mainCreator': 'Pritsak',
  'year': 1982,
  'title': 'The Hunnic Language of the Attila Clan'},
 {'key': 'X8T9XGG3',
  'itemType': 'book',
  'mainCreator': 'Anderson',
  'year': 2010,
  'title': 'A Place in Public: Women’s Rights in Meiji Japan'},
 {'key': 'S67VTPIP',
  'itemType': 'bookSection',
  'mainCreator': 'Shively_et_al',
  'year': 1999,
  'title': 'Introduction'},
 {'key': 'C6AIUKSD',
  'itemType': 'bookSection',
  'mainCreator': 'Hall_Nobuhiko_McClain',
  'year': 1991,
  'title': 'Commercial change and urban growth in early modern Japan'},
 {'key': '22QN7VJX',
  'itemType': 'book',
  'mainCreator': 'Hauser',
  'year': 1974,
  'title': 'Economic Institutional Change in Tokugawa Japan: Osaka and the Kinai Cotton Trade'},
 {'key': 'W2SUQ5DZ',
  'itemType': 'journalArticle',
  'mainCreator': 'Brown',
  'year': 1906,
  'title': 'OLD KASKASKIA DAYS AND WAYS'},
 {'key': 'A9W9P8TM',
  'itemType': 'journalArticle',
  'mainCreator': 'Murphy_et_al',
  'year': 2021,
  'title': 'Modernity is incompatible with planetary limits: Developing a PLAN for the future'},
 {'key': 'GX8I2DIE',
  'itemType': 'book',
  'mainCreator': 'Röhl',
  'year': 2004,
  'title': 'History of Law in Japan since 1868'},
 {'key': 'STA2IASG',
  'itemType': 'bookSection',
  'mainCreator': 'Röllicke_et_al',
  'year': 2015,
  'title': 'Some Brief Notes on Purity in Chinese Daoism'},
 {'key': 'SGQAJ2V2',
  'itemType': 'book',
  'mainCreator': 'Schmidt',
  'year': 2021,
  'title': 'Capital Punishment in Japan'},
 {'key': '3AP8UNQX',
  'itemType': 'journalArticle',
  'mainCreator': 'Pietrusewsky',
  'year': 2004,
  'title': 'Multivariate comparisons of female cranial series from the Ryukyu Islands and Japan'},
 {'key': 'JSWG9GA3',
  'itemType': 'bookSection',
  'mainCreator': 'Boyle_Bosworth',
  'year': 1968,
  'title': 'THE POLITICAL AND DYNASTIC HISTORY OF THE IRANIAN WORLD (A.D. 1000–1217)'},
 {'key': 'CT98X4FR',
  'itemType': 'book',
  'mainCreator': 'Lafferty',
  'year': 2013,
  'title': 'Law and Society in the Age of Theoderic the Great: A Study of the Edictum Theoderici'},
 {'key': 'QRHRJQAU',
  'itemType': 'book',
  'mainCreator': 'Lintott',
  'year': 1992,
  'title': 'Judicial Reform and Land Reform in the Roman Republic: A New Edition, with Translation and Commentary, of the Laws from Urbino'},
 {'key': 'BQ2WEWN6',
  'itemType': 'bookSection',
  'mainCreator': 'Mizoguchi',
  'year': 2013,
  'title': 'An Archaeology of Monuments: The Early Kofun (AD 275–400) and Middle Kofun Periods (AD 400–500)'},
 {'key': '74WUK9XA',
  'itemType': 'book',
  'mainCreator': 'Roosevelt',
  'year': 2009,
  'title': 'The Archaeology of Lydia, from Gyges to Alexander'},
 {'key': '24FJ2R6Q',
  'itemType': 'book',
  'mainCreator': 'Fleet',
  'year': 2004,
  'title': 'European and Islamic Trade in the Early Ottoman State: The Merchants of Genoa and Turkey'},
 {'key': 'JXVACSEM',
  'itemType': 'bookSection',
  'mainCreator': 'Cameron_Garnsey_Curran',
  'year': 1997,
  'title': 'From Jovian to Theodosius'},
 {'key': 'RTFA6M8F',
  'itemType': 'bookSection',
  'mainCreator': 'Fleet_Ocak',
  'year': 2009,
  'title': 'Social, cultural and intellectual life, 1071–1453'},
 {'key': 'CPEQXINQ',
  'itemType': 'book',
  'mainCreator': 'Kirch_Sahlins',
  'year': 1994,
  'title': 'Anahulu: The Anthropology of History in the Kingdom of Hawaii, Volume 1: Historical Ethnography'},
 {'key': 'HQQQPGZF',
  'itemType': 'bookSection',
  'mainCreator': 'Whita_Walker',
  'year': 2001,
  'title': 'Japan: Democracy in a Confucian-Based Society'},
 {'key': 'V59PDHCI',
  'itemType': 'book',
  'mainCreator': 'Daniel',
  'year': 2001,
  'title': 'The History of Iran'},
 {'key': '39E2JACP',
  'itemType': 'book',
  'mainCreator': 'Meens',
  'year': 2014,
  'title': 'Penance in Medieval Europe, 600–1200'},
 {'key': 'Q9JM4SCH',
  'itemType': 'book',
  'mainCreator': 'Rattray',
  'year': 1929,
  'title': 'Ashanti law and constitution'},
 {'key': 'E9S9A7RZ',
  'itemType': 'journalArticle',
  'mainCreator': 'Sudyka',
  'year': 2011,
  'title': 'The "Megalithic" Iron Age Culture in South India: Some General Remarks'},
 {'key': 'PWG8VZV6',
  'itemType': 'book',
  'mainCreator': 'Manuel',
  'year': 1989,
  'title': 'Ṭhumrī in Historical and Stylistic Perspectives'},
 {'key': 'W4W8P72T',
  'itemType': 'book',
  'mainCreator': 'Jager',
  'year': 2006,
  'title': 'The Last Duel: A True Story of Crime, Scandal, and Trial by Combat in Medieval France'},
 {'key': 'SGWSU5ZC',
  'itemType': 'book',
  'mainCreator': 'Harrison',
  'year': 2000,
  'title': 'Augustine: Christian Truth and Fractured Humanity'},
 {'key': 'HGJTIQW4',
  'itemType': 'book',
  'mainCreator': 'Cramb',
  'year': 1986,
  'title': 'The evolution of Iban land tenure'},
 {'key': 'SE3HWFFI',
  'itemType': 'book',
  'mainCreator': 'Vasiliev',
  'year': 1958,
  'title': 'History of the Byzantine Empire, 324–1453, Volume I'},
 {'key': 'TT65X6H2',
  'itemType': 'bookSection',
  'mainCreator': 'Grajetzki_Maree',
  'year': 2010,
  'title': 'Notes on administration in the second intermediate period'},
 {'key': 'KANHVJGN',
  'itemType': 'book',
  'mainCreator': 'Cohen',
  'year': 1993,
  'title': 'The Cultic Calendars of the Ancient Near East'},
 {'key': 'MIUA6CPE',
  'itemType': 'book',
  'mainCreator': 'Miller',
  'year': 2003,
  'title': 'The Orphans of Byzantium: Child Welfare in the Christian Empire'},
 {'key': 'GXF8S9J6',
  'itemType': 'book',
  'mainCreator': 'Cancik-Kirschbaum_Cristofori',
  'year': 2012,
  'title': 'Gli Assiri'},
 {'key': '52KEPQAT',
  'itemType': 'encyclopediaArticle',
  'mainCreator': 'Magdalene',
  'year': 2012,
  'title': 'Judicial and Legal Systems i: Achaemenid Judicial and Legal Systems'},
 {'key': 'H3CPBIQM',
  'itemType': 'bookSection',
  'mainCreator': 'Nijf_Stavrianopoulou',
  'year': 2013,
  'title': 'Ceremonies, Athletics and the City: Some Remarks on the Social Imaginary of the Greek City of the Hellenistic Period'},
 {'key': 'MU9VBDFC',
  'itemType': 'bookSection',
  'mainCreator': 'Macuch_et_al',
  'year': 2015,
  'title': 'Law in Pre-Modern Zoroastrianism'},
 {'key': '8NU8V4I2',
  'itemType': 'book',
  'mainCreator': 'Carter',
  'year': 2011,
  'title': 'Creating Catholics: Catechism and Primary Education in Early Modern France'},
 {'key': '7QN3X4W6',
  'itemType': 'journalArticle',
  'mainCreator': 'Marinatos',
  'year': 2005,
  'title': 'The ideals of manhood in Minoan Crete'},
 {'key': 'CTE4WCMI',
  'itemType': 'book',
  'mainCreator': 'Minerbi',
  'year': 1992,
  'title': 'Hawaiian Sanctuaries, Places of Refuge and Indigenous Knowledge in Hawaii'},
 {'key': 'GUFIPQ4X',
  'itemType': 'book',
  'mainCreator': 'Nicolle',
  'year': 2001,
  'title': 'The Crusades'},
 {'key': 'GD4VM32X',
  'itemType': 'bookSection',
  'mainCreator': 'Rawson_et_al',
  'year': 2001,
  'title': 'The Expansion of Rome'},
 {'key': 'S5X2ZF66',
  'itemType': 'journalArticle',
  'mainCreator': 'Nicholson',
  'year': 1994,
  'title': "The Delivery and Confidentiality of Cicero's Letters"},
 {'key': 'RHWVH2C5',
  'itemType': 'bookSection',
  'mainCreator': 'Anderson_Holt',
  'year': 2019,
  'title': 'The Idea of Power in Javanese Culture'},
 {'key': 'FRVN5QG5',
  'itemType': 'bookSection',
  'mainCreator': 'Tejada_Caller_et_al',
  'year': 2012,
  'title': 'From barter to coin: Shifting cognitive frames in Classical Greek economy'},
 {'key': 'CR6SWN6S',
  'itemType': 'book',
  'mainCreator': 'Bavarian',
  'year': 2005,
  'title': "Unearthing technology's influence on the ancient Chinese dynasties through metallurgical investigations"},
 {'key': 'PR4SH56E',
  'itemType': 'bookSection',
  'mainCreator': 'Wiesehöfer_Hagedorn_Kratz',
  'year': 2013,
  'title': 'Law and Religion in Achaemenid Iran'},
 {'key': '3VV5TV2H',
  'itemType': 'book',
  'mainCreator': 'Goldman',
  'year': 1970,
  'title': 'Ancient Polynesian Society'},
 {'key': '9H974BSS',
  'itemType': 'journalArticle',
  'mainCreator': 'Crocombe',
  'year': 1966,
  'title': 'A modern Orokaiva feast'},
 {'key': 'RMXJFZCQ',
  'itemType': 'journalArticle',
  'mainCreator': 'Driessen',
  'year': 2010,
  'title': 'The goddess and the skull: some observations on group identity in Prepalatial Crete'},
 {'key': 'BIQQNZGV',
  'itemType': 'journalArticle',
  'mainCreator': 'Buzon',
  'year': 2014,
  'title': 'Tombos during the Napatan period (∼750–660 BC): Exploring the consequences of sociopolitical transitions in ancient Nubia'},
 {'key': 'RR4Q7RVE',
  'itemType': 'bookSection',
  'mainCreator': 'Gee',
  'year': 2002,
  'title': 'Oracle by Image: Coffin Text 103 in Context'},
 {'key': '6G285FKC',
  'itemType': 'book',
  'mainCreator': 'Wang',
  'year': 2002,
  'title': 'Ming Qing sheng huo lüe ying: a glimpse of life in Ming and Qing dynasties'},
 {'key': 'B5TCWHCW',
  'itemType': 'journalArticle',
  'mainCreator': 'Beckman',
  'year': 2011,
  'title': 'Blood in Hittite Ritual'},
 {'key': 'E6FG3G4E',
  'itemType': 'bookSection',
  'mainCreator': 'Forbes_Brown_et_al',
  'year': 1902,
  'title': 'Venice'},
 {'key': '6DSH3477',
  'itemType': 'book',
  'mainCreator': 'Baker_Phongpaichit',
  'year': 2005,
  'title': 'A History of Thailand'},
 {'key': '9U6JKRFG',
  'itemType': 'book',
  'mainCreator': 'Baker_Phongpaichit',
  'year': 2009,
  'title': 'A History of Thailand'},
 {'key': 'SNVTP63Z',
  'itemType': 'book',
  'mainCreator': 'Gibbons',
  'year': 1830,
  'title': 'The History of the Decline and Fall of the Roman Empire'},
 {'key': 'MGKZMJHX',
  'itemType': 'journalArticle',
  'mainCreator': 'Collins',
  'year': 1990,
  'title': 'The Puppy in Hittite Ritual'},
 {'key': 'BJ2CPGR4',
  'itemType': 'book',
  'mainCreator': 'Bunson',
  'year': 2009,
  'title': 'Encyclopedia of the Roman Empire'},
 {'key': '49W8PAAS',
  'itemType': 'book',
  'mainCreator': 'Thompson',
  'year': 1996,
  'title': 'The Huns'},
 {'key': 'PTE6A7VU',
  'itemType': 'bookSection',
  'mainCreator': 'Sanders',
  'year': 2008,
  'title': 'The Fatimid State, 969-1171'},
 {'key': 'JTZ649NI',
  'itemType': 'book',
  'mainCreator': 'Marzano',
  'year': 2007,
  'title': 'Roman Villas in Central Italy: A Social and Economic History'},
 {'key': 'AWSB5MQV',
  'itemType': 'book',
  'mainCreator': 'Raz',
  'year': 1983,
  'title': 'Audience and Actors: A Study of Their Interaction in the Japanese Traditional Theatre'},
 {'key': 'UB82GTSG',
  'itemType': 'bookSection',
  'mainCreator': 'Radding_Ciaralli',
  'year': 2006,
  'title': 'The Corpus Iuris Civilis in the Middle Ages: Manuscripts and Transmission from the Sixth Century to the Juristic Revival'},
 {'key': 'NM8ZQNK5',
  'itemType': 'book',
  'mainCreator': 'Sato',
  'year': 2021,
  'title': 'State and Rural Society in Medieval Islam: Sultans, Muqta‘s and Fallahun'},
 {'key': 'PV3GQNB2',
  'itemType': 'book',
  'mainCreator': 'Lev',
  'year': 2022,
  'title': 'State and Society in Fatimid Egypt'},
 {'key': 'ZRFJCVKR',
  'itemType': 'book',
  'mainCreator': 'Hamblin',
  'year': 2013,
  'title': 'Warfare in the Ancient Near East to 1600 BC: Holy Warriors at the Dawn of History'},
 {'key': '4NRH985K',
  'itemType': 'book',
  'mainCreator': 'Dale',
  'year': 2009,
  'title': 'The Muslim Empires of the Ottomans, Safavids, and Mughals'},
 {'key': 'M2PWUWM4',
  'itemType': 'journalArticle',
  'mainCreator': 'Nasr',
  'year': 1974,
  'title': 'Religion in Safavid Persia'},
 {'key': '4B4CT4V8',
  'itemType': 'book',
  'mainCreator': 'Keyvani',
  'year': 1982,
  'title': 'Artisans and Guild Life in the Later Safavid Period: Contributions to the Social-economic History of Persia'},
 {'key': '8E3T7RUW',
  'itemType': 'journalArticle',
  'mainCreator': 'Golombek',
  'year': 1974,
  'title': 'Urban Patterns in Pre-Safavid Isfahan'},
 {'key': 'JNSNK2UZ',
  'itemType': 'bookSection',
  'mainCreator': 'Lockhart_Jackson_Hillenbrand',
  'year': 1986,
  'title': 'SAFAVID ARCHITECTURE'},
 {'key': 'SSNGEK44',
  'itemType': 'webpage',
  'mainCreator': 'Illinois_State_Museum',
  'year': 2000,
  'title': 'Society: Neighbours: Enemies'},
 {'key': 'AIBZUJCC',
  'itemType': 'webpage',
  'mainCreator': 'Illinois_State_Museum',
  'year': 2000,
  'title': 'Identity'},
 {'key': 'JV5ADAA4',
  'itemType': 'webpage',
  'mainCreator': 'Illinois_State_Museum',
  'year': 2000,
  'title': 'History'},
 {'key': 'N5RIATUA',
  'itemType': 'book',
  'mainCreator': 'Matthee',
  'year': 2011,
  'title': 'Persia in Crisis: Safavid Decline and the Fall of Isfahan'},
 {'key': 'IGQD3R5N',
  'itemType': 'webpage',
  'mainCreator': 'Illinois_State_Museum',
  'year': 2000,
  'title': 'Society: Neighbors: The French'},
 {'key': 'G3UBF424',
  'itemType': 'webpage',
  'mainCreator': 'Illinois_State_Museum',
  'year': 2000,
  'title': 'Identity: Language'},
 {'key': 'TGECPH2Q',
  'itemType': 'webpage',
  'mainCreator': 'Illinois_State_Museum',
  'year': 2000,
  'title': 'History: Exploration'},
 {'key': 'JE6SE5MF',
  'itemType': 'bookSection',
  'mainCreator': 'Twitchett_Loewe_Ying-Shih',
  'year': 1986,
  'title': 'Han foreign relations'},
 {'key': 'CMGAVQJG',
  'itemType': 'webpage',
  'mainCreator': 'Illinois_State_Museum',
  'year': 2000,
  'title': 'Society: Leaders'},
 {'key': 'MT6FA9S7',
  'itemType': 'webpage',
  'mainCreator': 'Illinois_State_Museum',
  'year': 2000,
  'title': 'Technology: Houses'},
 {'key': 'UUN792HC',
  'itemType': 'webpage',
  'mainCreator': 'Illinois_State_Museum',
  'year': 2000,
  'title': 'Tools and Utensils'},
 {'key': 'WWWV8E4I',
  'itemType': 'bookSection',
  'mainCreator': 'Lai_Popkin',
  'year': 1999,
  'title': 'CHINA AND WESTERN PHILOSOPHY IN THE AGE OF REASON'},
 {'key': 'WXI6TQD7',
  'itemType': 'webpage',
  'mainCreator': 'Illinois_State_Museum',
  'year': 2000,
  'title': 'Warfare'},
 {'key': 'XN3FU6T4',
  'itemType': 'webpage',
  'mainCreator': 'Illinois_State_Museum',
  'year': 2000,
  'title': 'Illinois Economy: Settlements'},
 {'key': '9MFV2E8X',
  'itemType': 'webpage',
  'mainCreator': 'Illinois_State_Museum',
  'year': 2000,
  'title': 'Decline'},
 {'key': '5E9UPZ7Q',
  'itemType': 'webpage',
  'mainCreator': 'Illinois_State_Museum',
  'year': 2000,
  'title': 'Society'},
 {'key': 'TSDZP9EP',
  'itemType': 'book',
  'mainCreator': 'Warren',
  'year': 1975,
  'title': 'The Techiman-Bono of Ghana: An Ethnography of an Akan Society'},
 {'key': 'MMV7SB6I',
  'itemType': 'bookSection',
  'mainCreator': 'Twitchett_Dalby',
  'year': 1979,
  'title': "Court politics in late T'ang times"},
 {'key': '3WAWNGJG',
  'itemType': 'webpage',
  'mainCreator': 'Illinois_State_Museum',
  'year': 2000,
  'title': 'The Illinois Indians: Archaeology: Starved Rock Site'},
 {'key': '4UZXE8NN',
  'itemType': 'bookSection',
  'mainCreator': 'Twitchett_Chaffee_McKnight',
  'year': 2015,
  'title': 'Chinese law and legal system: Five Dynasties and Sung'},
 {'key': '5N7PI243',
  'itemType': 'webpage',
  'mainCreator': 'Illinois_State_Museum',
  'year': 2000,
  'title': 'Economy: Food: Agriculture'},
 {'key': 'IJ4K3HQ3',
  'itemType': 'journalArticle',
  'mainCreator': 'Powell',
  'year': 1996,
  'title': 'Money in Mesopotamia'},
 {'key': '2ZRC3HDX',
  'itemType': 'webpage',
  'mainCreator': 'Illinois_State_Museum',
  'year': 2000,
  'title': 'Beliefs: Health'},
 {'key': '67BUA4WB',
  'itemType': 'webpage',
  'mainCreator': 'Illinois_State_Museum',
  'year': 2000,
  'title': 'Art and Music: Art'},
 {'key': 'PNEZMEBJ',
  'itemType': 'encyclopediaArticle',
  'mainCreator': 'Gerson',
  'year': 1995,
  'title': 'Pilgrimage'},
 {'key': 'VWNEDKQ2',
  'itemType': 'webpage',
  'mainCreator': 'Illinois_State_Museum',
  'year': 2000,
  'title': "Archaeology: River L'Abbe Mission Site"},
 {'key': 'CK6NPGJX',
  'itemType': 'webpage',
  'mainCreator': 'Illinois_State_Museum',
  'year': 2000,
  'title': "Archaeology: River L'Abbe Mission Site"},
 {'key': 'WXEJMIQV',
  'itemType': 'webpage',
  'mainCreator': 'Illinois_State_Museum',
  'year': 2000,
  'title': 'Society: Recreation'},
 {'key': 'RI3BKXSV',
  'itemType': 'webpage',
  'mainCreator': 'Illinois_State_Museum',
  'year': 2000,
  'title': 'Economy: Trade'},
 {'key': 'RATP9XJC',
  'itemType': 'webpage',
  'mainCreator': 'Illinois_State_Museum',
  'year': 2000,
  'title': 'History: European Contact'},
 {'key': 'NEUWFGXM',
  'itemType': 'webpage',
  'mainCreator': 'Illinois_State_Museum',
  'year': 2000,
  'title': 'Identity: Appearance'},
 {'key': 'UTZF4MT8',
  'itemType': 'bookSection',
  'mainCreator': 'MacDonald',
  'year': 2015,
  'title': "‘A Chacun son Bambara', encore une fois: History, Archaeology, and Bambara Origins"},
 {'key': 'F4B284BS',
  'itemType': 'webpage',
  'mainCreator': 'Illinois_State_Museum',
  'year': 2000,
  'title': 'Economy: Trade'},
 {'key': '2R7SVRWK',
  'itemType': 'webpage',
  'mainCreator': 'Illinois_State_Museum',
  'year': 2000,
  'title': 'Late Prehistoric, Technology: Weapons'},
 {'key': '222PSGFP',
  'itemType': 'webpage',
  'mainCreator': 'Illinois_State_Museum',
  'year': 2000,
  'title': 'Late Prehistoric, Technology: Weapons'},
 {'key': 'I83RQCZC',
  'itemType': 'bookSection',
  'mainCreator': 'Sediyawati_Schutte',
  'year': 1994,
  'title': 'The State Formation of Kadiri'},
 {'key': 'V3MAD4M4',
  'itemType': 'bookSection',
  'mainCreator': 'NO_CREATOR',
  'year': 0,
  'title': 'The State Formation of Kadiri'},
 {'key': 'F8G5IXZV',
  'itemType': 'book',
  'mainCreator': 'Stein',
  'year': 2010,
  'title': 'A History of India'},
 {'key': 'BDBBA4WF',
  'itemType': 'bookSection',
  'mainCreator': 'Peacock_Shaw',
  'year': 2000,
  'title': 'The Roman period (30 BC-AD 395)'},
 {'key': 'FP4SKG5T',
  'itemType': 'bookSection',
  'mainCreator': 'Bosworth',
  'year': 2001,
  'title': 'Turks, Seljuk and Ottoman'},
 {'key': 'TIKDEBMH',
  'itemType': 'bookSection',
  'mainCreator': 'Lin',
  'year': 2014,
  'title': "The Characteristics of China's Traditional Economy"},
 {'key': 'EI82Q96X',
  'itemType': 'journalArticle',
  'mainCreator': 'NO_CREATOR',
  'year': 1994,
  'title': 'The Law of the Splintered Paddle: Kānāwai Māmalahoe'},
 {'key': 'DZB23F5N',
  'itemType': 'encyclopediaArticle',
  'mainCreator': 'Mitchell',
  'year': 2006,
  'title': 'Samanids'},
 {'key': 'Q3YPGAGJ',
  'itemType': 'book',
  'mainCreator': 'Durrenberger',
  'year': 1989,
  'title': 'Anthropological perspectives on the commonwealth period'},
 {'key': '4Z2I4JRA',
  'itemType': 'journalArticle',
  'mainCreator': 'Rooney',
  'year': 2004,
  'title': 'Angkor—Before and After:\nA Cultural History of the Khmers (Review)'},
 {'key': 'Z8MEV99Q',
  'itemType': 'webpage',
  'mainCreator': 'NO_CREATOR',
  'year': 0,
  'title': 'Orchid Press - Book Review - Angkor—Before and After'},
 {'key': 'I9FBAPZC',
  'itemType': 'book',
  'mainCreator': 'Fogelin',
  'year': 2006,
  'title': 'Archaeology of Early Buddhism'},
 {'key': '8CZNZ7MB',
  'itemType': 'conferencePaper',
  'mainCreator': 'Colditz',
  'year': 1998,
  'title': 'Notes on the problem of punishment and conversion in Manichaeism'},
 {'key': '2U2QPMSW',
  'itemType': 'book',
  'mainCreator': 'Faure',
  'year': 2003,
  'title': 'The Power of Denial: Buddhism, Purity, and Gender'},
 {'key': 'PBR2NAU7',
  'itemType': 'book',
  'mainCreator': 'NO_CREATOR',
  'year': 2009,
  'title': 'The Power of Denial'},
 {'key': 'QEWRPCFW',
  'itemType': 'book',
  'mainCreator': 'NO_CREATOR',
  'year': 2003,
  'title': 'The Power of Denial'},
 {'key': 'B25RZPWH',
  'itemType': 'bookSection',
  'mainCreator': 'Insoll',
  'year': 2011,
  'title': 'Sub-Saharan Africa'},
 {'key': '5CN6TVWV',
  'itemType': 'bookSection',
  'mainCreator': 'Younger',
  'year': 1995,
  'title': 'Bronze Age Representations of Aegean Bull-Games, III'},
 {'key': 'EU8XSPWK',
  'itemType': 'bookSection',
  'mainCreator': 'Cole',
  'year': 2006,
  'title': 'Buddhism'},
 {'key': 'ZR538MHG',
  'itemType': 'thesis',
  'mainCreator': 'Lee',
  'year': 1999,
  'title': "The new year's festivals and the shrine of Ali Ibn Abi Talib Sy Mazar-I-Sharif, Afghanistan"},
 {'key': '2QG2I73Q',
  'itemType': 'book',
  'mainCreator': 'Oates',
  'year': 1986,
  'title': 'Babylon'},
 {'key': 'I9XK6VMI',
  'itemType': 'book',
  'mainCreator': 'Bowden',
  'year': 2010,
  'title': 'Mystery Cults of the Ancient World'},
 {'key': '3N8IYWTP',
  'itemType': 'encyclopediaArticle',
  'mainCreator': 'Papio',
  'year': 2004,
  'title': 'Slavery'},
 {'key': 'CDU5Y6E5',
  'itemType': 'journalArticle',
  'mainCreator': 'Soles',
  'year': 2010,
  'title': 'Evidence for ancestor worship in Minoan Crete: new finds from Mochlos'},
 {'key': '7NEEWEPP',
  'itemType': 'journalArticle',
  'mainCreator': 'Nikolenko',
  'year': 1962,
  'title': 'The Castle Balalyk-Tepe; A Contribution to the History of Material Culture and the Art of Tokharestan (In Russian)'},
 {'key': 'RLWG8CKS',
  'itemType': 'book',
  'mainCreator': 'Doniger',
  'year': 1988,
  'title': 'Textual Sources for the Study of Hinduism'},
 {'key': '22CAEEUQ',
  'itemType': 'book',
  'mainCreator': 'Malo',
  'year': 1903,
  'title': 'Hawaiian Antiquities (Moolelo Hawaii) Translated by Dr N. B. Emerson'},
 {'key': 'ZDNA83DC',
  'itemType': 'book',
  'mainCreator': 'Meri',
  'year': 2006,
  'title': 'Medieval Islamic Civilization: An Encyclopedia'},
 {'key': 'NCDATP6U',
  'itemType': 'book',
  'mainCreator': 'Kelly',
  'year': 2009,
  'title': 'The End of Empire: Attila the Hun and the Fall of Rome'},
 {'key': 'KT28UNNE',
  'itemType': 'encyclopediaArticle',
  'mainCreator': 'Hasenstab',
  'year': 2001,
  'title': 'Proto-Iroquois'},
 {'key': 'URK4RXUA',
  'itemType': 'bookSection',
  'mainCreator': 'Emerson',
  'year': 1997,
  'title': 'Cahokian Elite Ideology and the Mississippian Cosmos'},
 {'key': 'SATA9RX9',
  'itemType': 'bookSection',
  'mainCreator': 'Deweese',
  'year': 2009,
  'title': 'Islamization in the Mongol Empire'},
 {'key': 'RRF2RFJV',
  'itemType': 'blogPost',
  'mainCreator': 'Marshak',
  'year': 2003,
  'title': 'The Archaeology of Sogdiana'},
 {'key': 'ZN9N624X',
  'itemType': 'book',
  'mainCreator': 'Kennedy',
  'year': 2002,
  'title': 'Mongols, Huns and Vikings: Nomads at War'},
 {'key': 'MJUKWUI8',
  'itemType': 'webpage',
  'mainCreator': 'NO_CREATOR',
  'year': 0,
  'title': "Was A 'Mistress Of The Lionesses' A King In Ancient Canaan?"},
 {'key': 'M786RE39',
  'itemType': 'book',
  'mainCreator': 'Kautilya',
  'year': 2000,
  'title': 'The ARTHASHASTRA'},
 {'key': '9958XPPW',
  'itemType': 'bookSection',
  'mainCreator': 'Peyronel_et_al',
  'year': 2018,
  'title': 'The Old Elamite Period'},
 {'key': '2GCW36FF',
  'itemType': 'bookSection',
  'mainCreator': 'Reid_Morgan_Amitai',
  'year': 2010,
  'title': 'Armies and their economic basis in Iran and the surrounding lands, c. 1000–1500'},
 {'key': 'KV6J6BXS',
  'itemType': 'encyclopediaArticle',
  'mainCreator': 'Margill',
  'year': 1998,
  'title': 'Mahmud Ghazan'},
 {'key': '4BG7C8KR',
  'itemType': 'book',
  'mainCreator': 'Eastburn',
  'year': 2015,
  'title': 'The Esoteric Codex: Zoroastrianism'},
 {'key': 'IR6A7G7A',
  'itemType': 'journalArticle',
  'mainCreator': 'Novak_Slaus',
  'year': 2012,
  'title': 'Frequency and patterning of bone trauma in the late medieval population (13th-16th century) from Dugopolje, southern Croatia'},
 {'key': 'AH4IM7GU',
  'itemType': 'book',
  'mainCreator': 'Strabo_Jones',
  'year': 1924,
  'title': 'The Geography of Strabo'},
 {'key': 'GKK6D6ZF',
  'itemType': 'journalArticle',
  'mainCreator': 'Greene',
  'year': 2012,
  'title': 'Nature and Empire in Ottoman Egypt: An Environmental History (review)'},
 {'key': 'UQWQJU88',
  'itemType': 'blogPost',
  'mainCreator': 'admin',
  'year': 2019,
  'title': 'The Future of Food: Getting Beyond the Energy Blindness of Techno-Utopianism'},
 {'key': 'S5GFV8FB',
  'itemType': 'journalArticle',
  'mainCreator': 'Springer',
  'year': 1981,
  'title': 'An Ethnohistoric Study of the Smoking Complex in Eastern North America'},
 {'key': 'FTG9H8NG',
  'itemType': 'book',
  'mainCreator': 'Petrovich_Petrovich',
  'year': 2016,
  'title': 'Inner Purity and Pollution in Greek Religion: Volume I: Early Greek Religion'},
 {'key': 'S232VC3Q',
  'itemType': 'bookSection',
  'mainCreator': 'Lawrence',
  'year': 2013,
  'title': 'Muslim engagement with injustice and violence'},
 {'key': '45U3WUGJ',
  'itemType': 'book',
  'mainCreator': 'Habibullah',
  'year': 1961,
  'title': 'The foundation of Muslim rule in India'},
 {'key': 'TJN32UQ5',
  'itemType': 'book',
  'mainCreator': 'Berger',
  'year': 1968,
  'title': 'Encyclopedic Dictionary of Roman Law'},
 {'key': 'H6UE3ZSK',
  'itemType': 'book',
  'mainCreator': 'Carlson',
  'year': 2010,
  'title': 'Performing Bodies in Pain: Medieval and Post-Modern Martyrs, Mystics, and Artists'},
 {'key': 'GR8XHAMG',
  'itemType': 'book',
  'mainCreator': 'Edwards',
  'year': 1993,
  'title': 'The Politics of Immorality in Ancient Rome'},
 {'key': 'KITTDZU7',
  'itemType': 'bookSection',
  'mainCreator': 'Horster',
  'year': 2008,
  'title': 'Living on Religion: Professionals and Personnel'},
 {'key': '5I95696A',
  'itemType': 'journalArticle',
  'mainCreator': 'Kronenfeld',
  'year': 1999,
  'title': 'Fanti Kinship: Language, Inheritance, And Kin Groups'},
 {'key': 'V7E45ZWN',
  'itemType': 'journalArticle',
  'mainCreator': 'Hussain',
  'year': 2005,
  'title': 'The Mourning of History and the History of Mourning: The Evolution of Ritual Commemoration of the Battle of Karbala.'},
 {'key': '5EKPPB2E',
  'itemType': 'bookSection',
  'mainCreator': 'Sanders',
  'year': 1998,
  'title': 'The Fatimid state, 969-1171'},
 {'key': 'PPDI9F4I',
  'itemType': 'book',
  'mainCreator': 'Butler',
  'year': 2007,
  'title': 'New World Faiths: Religion in Colonial America'},
 {'key': 'PIUEISAT',
  'itemType': 'book',
  'mainCreator': 'Christakis',
  'year': 2014,
  'title': "The Sanctuary of Hermes and Aphrodite at Syme Viannou. V, Sēmeía keraméōn: Potters' marks from Syme and other sites of Bronze Age Crete / Kostis S. Christakis."},
 {'key': 'UVECBVP7',
  'itemType': 'book',
  'mainCreator': 'Collett',
  'year': 2005,
  'title': 'The Butcher of Amritsar: General Reginald Dyer'},
 {'key': 'U4BXHF38',
  'itemType': 'book',
  'mainCreator': 'Christiansen',
  'year': 2005,
  'title': 'Tradition summary: Late Eastern Woodland'},
 {'key': 'ZJVWWN24',
  'itemType': 'book',
  'mainCreator': 'Julien_et_al',
  'year': 1970,
  'title': 'History of North Africa: Tunisia, Algeria, Morocco, From the Arab Conquest to 1830'},
 {'key': 'QDWZF6JW',
  'itemType': 'book',
  'mainCreator': 'Turnbull',
  'year': 2008,
  'title': 'The Samurai Invasion of Korea, 1592-98'},
 {'key': 'WTWBA49S',
  'itemType': 'book',
  'mainCreator': 'Evans',
  'year': 2008,
  'title': 'Daily Life in the Hellenistic Age\nFrom Alexander to Cleopatra'},
 {'key': 'HRSQBUJP',
  'itemType': 'bookSection',
  'mainCreator': 'Quirke',
  'year': 2001,
  'title': 'Judgment of the Dead'},
 {'key': '7BUB5FUT',
  'itemType': 'bookSection',
  'mainCreator': 'Wilfong',
  'year': 2001,
  'title': 'Marriage and Divorce'},
 {'key': 'D64QPGWM',
  'itemType': 'bookSection',
  'mainCreator': 'Luft',
  'year': 2001,
  'title': 'Religion'},
 {'key': 'J2INB38B',
  'itemType': 'bookSection',
  'mainCreator': 'Doxey',
  'year': 2001,
  'title': 'Priesthood'},
 {'key': 'GCAB7MTR',
  'itemType': 'bookSection',
  'mainCreator': 'Silverman',
  'year': 2001,
  'title': 'Deities'},
 {'key': 'XG6A24EM',
  'itemType': 'bookSection',
  'mainCreator': 'Davidovich_Asimov_Bosworth',
  'year': 1998,
  'title': 'The Karakhanids'},
 {'key': 'X2I23UHZ',
  'itemType': 'encyclopediaArticle',
  'mainCreator': 'McGuiness',
  'year': 2003,
  'title': 'Sin (Theology Of)'},
 {'key': 'RZMC7BMZ',
  'itemType': 'encyclopediaArticle',
  'mainCreator': 'Lachowski',
  'year': 2003,
  'title': 'Sin (in the Bible)'},
 {'key': 'UH94RHHM',
  'itemType': 'bookSection',
  'mainCreator': 'Koshelenko_et_al',
  'year': 1994,
  'title': 'Parthia'},
 {'key': 'GI7H6WH8',
  'itemType': 'bookSection',
  'mainCreator': 'Meadows_et_al',
  'year': 2014,
  'title': 'The Lemuria: State Level “Magic” in the First Century AD?'},
 {'key': '8VNJ9I87',
  'itemType': 'bookSection',
  'mainCreator': 'Halstead_et_al',
  'year': 2011,
  'title': 'Political cuisine: rituals of commensality in the Neolithic and Bronze Age Aegean'},
 {'key': 'HUC5W7ET',
  'itemType': 'encyclopediaArticle',
  'mainCreator': 'Boulton_et_al',
  'year': 1995,
  'title': 'Armor and Weapons'},
 {'key': 'FEJ6MBG4',
  'itemType': 'encyclopediaArticle',
  'mainCreator': 'McGuinness',
  'year': 2003,
  'title': 'Sin (Theology of)'},
 {'key': 'IWI4CA2H',
  'itemType': 'encyclopediaArticle',
  'mainCreator': 'Sullivan',
  'year': 2003,
  'title': 'Merit'},
 {'key': 'AXP749KS',
  'itemType': 'encyclopediaArticle',
  'mainCreator': 'Lachowski',
  'year': 2003,
  'title': 'Sin (In the Bible)'},
 {'key': 'H34BJ766',
  'itemType': 'journalArticle',
  'mainCreator': 'Gilhus',
  'year': 1990,
  'title': 'Carnival in Religion: The Feast of Fools in France'},
 {'key': '4TDQ8NBW',
  'itemType': 'bookSection',
  'mainCreator': 'Altenmüller_Schwaiger',
  'year': 2001,
  'title': 'Hunting'},
 {'key': 'BTZHDEPC',
  'itemType': 'book',
  'mainCreator': 'Meyerowitz',
  'year': 1974,
  'title': 'The early history of the Akan states of Ghana'},
 {'key': '6IVDNMEP',
  'itemType': 'book',
  'mainCreator': 'Shamasastry',
  'year': 1915,
  'title': "Kautilya's Arthaśāstra. Translated by R. Shamasastry. With an introductory note by J.F. Fleet"},
 {'key': '63W7VF9W',
  'itemType': 'journalArticle',
  'mainCreator': 'Miner',
  'year': 1942,
  'title': 'Songhoi Circumcision'},
 {'key': '85232W9U',
  'itemType': 'journalArticle',
  'mainCreator': 'Hodous',
  'year': 2013,
  'title': 'The Quriltai as a Legal Institution in the Mongol Empire'},
 {'key': 'K44U39NW',
  'itemType': 'bookSection',
  'mainCreator': 'Smith_Brandt_Iddeng',
  'year': 2012,
  'title': 'The Feriae Latinae'},
 {'key': 'M652STT9',
  'itemType': 'bookSection',
  'mainCreator': 'McDowell',
  'year': 2001,
  'title': 'Crime and Punishment'},
 {'key': '3RTTIF3F',
  'itemType': 'book',
  'mainCreator': 'Warren',
  'year': 1988,
  'title': 'Minoan Religion as Ritual Action'},
 {'key': 'IXB4KBAP',
  'itemType': 'bookSection',
  'mainCreator': 'Twitchett_et_al',
  'year': 2015,
  'title': 'A history of the Sung military'},
 {'key': 'UEEEDV6X',
  'itemType': 'encyclopediaArticle',
  'mainCreator': 'Sundermann',
  'year': 1989,
  'title': 'Bema'},
 {'key': 'S5A5E9Q9',
  'itemType': 'encyclopediaArticle',
  'mainCreator': 'Chelkowski',
  'year': 2009,
  'title': "Ta'zia"},
 {'key': 'MJQH9H3N',
  'itemType': 'journalArticle',
  'mainCreator': 'Schneider',
  'year': 1986,
  'title': 'Mortification on Parade: Penitential Processions in Sixteenth- and Seventeenth-Century France'},
 {'key': '4SGG5Z9J',
  'itemType': 'bookSection',
  'mainCreator': 'Nathan_French_Ruppert',
  'year': 2014,
  'title': 'Buddhism and Law in Japan'},
 {'key': 'CF4PCZUR',
  'itemType': 'book',
  'mainCreator': 'McIntosh',
  'year': 1990,
  'title': 'Jenne-Jeno, an Ancient African City'},
 {'key': 'I2T8722S',
  'itemType': 'encyclopediaArticle',
  'mainCreator': 'Sundermann',
  'year': 2012,
  'title': 'FESTIVALS ii. MANICHEAN'},
 {'key': 'FPKHE8K7',
  'itemType': 'journalArticle',
  'mainCreator': 'Stausberg',
  'year': 2009,
  'title': 'Hell in Zoroastrian History'},
 {'key': 'K3555H4K',
  'itemType': 'book',
  'mainCreator': 'Willetts',
  'year': 1962,
  'title': 'Cretan Cults and Festivals'},
 {'key': 'NG87X6J5',
  'itemType': 'book',
  'mainCreator': 'Kerr',
  'year': 2004,
  'title': 'A General History and Collection of Voyages and Travels — Volume 01Arranged in Systematic Order: Forming a Complete History of the Origin and Progress of Navigation, Discovery, and Commerce, by Sea and Land, from the Earliest Ages to the Present Time'},
 {'key': 'HCWRZVGP',
  'itemType': 'book',
  'mainCreator': 'Fréderic_Lowe',
  'year': 1972,
  'title': 'Daily Life in Japan at the time of the Samurai, 1185–1603'},
 {'key': '29943VC4',
  'itemType': 'book',
  'mainCreator': 'Meyer',
  'year': 1999,
  'title': 'The Ancient Mysteries: A Sourcebook of Sacred Texts'},
 {'key': 'JXEXQVJX',
  'itemType': 'journalArticle',
  'mainCreator': 'Thompson',
  'year': 1989,
  'title': 'On the Prehistory of Hell in China'},
 {'key': '769HJ3B6',
  'itemType': 'conferencePaper',
  'mainCreator': 'Dye',
  'year': 2009,
  'title': 'War Honor and Tattoos: Mississippian Soul Capture'},
 {'key': 'UMX69U5N',
  'itemType': 'book',
  'mainCreator': 'Katz',
  'year': 2009,
  'title': 'Divine Justice: Religion and the Development of Chinese Legal Culture'},
 {'key': 'PFXCHNQ6',
  'itemType': 'book',
  'mainCreator': 'Mango',
  'year': 1980,
  'title': 'Byzantium: The Empire of New Rome'},
 {'key': 'RIDDJTWW',
  'itemType': 'bookSection',
  'mainCreator': 'Talbot_Cavallo',
  'year': 1997,
  'title': 'Women'},
 {'key': '6UCAQU8R',
  'itemType': 'journalArticle',
  'mainCreator': 'Malo',
  'year': 1951,
  'title': 'Hawaiian Antiquities (Moʻolelo Hawaiʻi)'},
 {'key': 'PBM3L3KQ',
  'itemType': 'bookSection',
  'mainCreator': 'Di_Cosmo',
  'year': 1999,
  'title': 'Manchu shamanic ceremonies at the Qing court'},
 {'key': '5XRJW88F',
  'itemType': 'encyclopediaArticle',
  'mainCreator': 'Esposito',
  'year': 2014,
  'title': 'Law'},
 {'key': 'S2HJZMHZ',
  'itemType': 'book',
  'mainCreator': 'Chandler',
  'year': 2008,
  'title': 'A History of Cambodia'},
 {'key': 'VJRXBD8J',
  'itemType': 'encyclopediaArticle',
  'mainCreator': 'Ockinga',
  'year': 2001,
  'title': 'Ethics and Morality'},
 {'key': 'MV3MW3IX',
  'itemType': 'encyclopediaArticle',
  'mainCreator': 'McKinnon',
  'year': 1995,
  'title': 'Mass, Chants and Texts'},
 {'key': '2WWHM8TU',
  'itemType': 'book',
  'mainCreator': 'Ikegami',
  'year': 1997,
  'title': 'The Taming of the Samurai: Honorific Individualism and the Making of Modern Japan'},
 {'key': 'H57UFNTB',
  'itemType': 'book',
  'mainCreator': 'Turnbull',
  'year': 1996,
  'title': 'The Samurai: A Military History'},
 {'key': '3XZXFXQT',
  'itemType': 'book',
  'mainCreator': 'Shoshan',
  'year': 1993,
  'title': 'Popular Culture in Medieval Cairo'},
 {'key': '8WTX8S4F',
  'itemType': 'book',
  'mainCreator': "O'Connor",
  'year': 2015,
  'title': 'The Never-ending Feast: The Anthropology and Archaeology of Feasting'},
 {'key': 'NX2VCI4B',
  'itemType': 'book',
  'mainCreator': 'Mathur',
  'year': 2007,
  'title': 'Medieval Hindu Law: Historical Evolution and Enlightened Rebellion'},
 {'key': 'HCMT5EKW',
  'itemType': 'book',
  'mainCreator': 'Wechsler',
  'year': 1985,
  'title': "Offerings of Jade and Silk: Ritual and Symbol in the Legitimation of the T'ang Dynasty"},
 {'key': '73D95VFF',
  'itemType': 'book',
  'mainCreator': 'Murphey',
  'year': 2008,
  'title': 'Exploring Ottoman Sovereignty: Tradition, Image and Practice in the Ottoman Imperial Household, 1400-1800'},
 {'key': 'UW2F6BCG',
  'itemType': 'bookSection',
  'mainCreator': 'Nelson_Theuws_Nelson',
  'year': 2000,
  'title': 'Carolingian royal funerals'},
 {'key': 'UT6C6KR4',
  'itemType': 'book',
  'mainCreator': 'Arnold',
  'year': 2005,
  'title': 'Belief and Unbelief in Medieval Europe'},
 {'key': 'KZ3XQX3B',
  'itemType': 'book',
  'mainCreator': 'Hassrick',
  'year': 1964,
  'title': 'The Sioux: life and customs of a warrior society'},
 {'key': 'NQSJZFPH',
  'itemType': 'bookSection',
  'mainCreator': 'Bryant_Bak',
  'year': 1990,
  'title': 'The Medieval Entry Ceremony at Paris'},
 {'key': 'FNJD6HZD',
  'itemType': 'book',
  'mainCreator': 'Rohe_Goldbloom',
  'year': 2014,
  'title': 'Islamic Law in Past and Present'},
 {'key': 'K4IFZ23D',
  'itemType': 'journalArticle',
  'mainCreator': 'Ffoulkes',
  'year': 1909,
  'title': 'Fanti marriage customs'},
 {'key': 'GCCBGWMM',
  'itemType': 'book',
  'mainCreator': 'Koentjaraningrat',
  'year': 1985,
  'title': 'Javanese Culture'},
 {'key': '2EPKK7NW',
  'itemType': 'book',
  'mainCreator': 'Coe_Koontz',
  'year': 2013,
  'title': 'Mexico: from the Olmecs to the Aztecs'},
 {'key': '869Q3EQ4',
  'itemType': 'book',
  'mainCreator': 'Whiting',
  'year': 2016,
  'title': 'Buddhism in Thailand - a guide for expats and visitors'},
 {'key': '57H66EJ3',
  'itemType': 'book',
  'mainCreator': 'Muir',
  'year': 1981,
  'title': 'Civic Ritual in Renaissance Venice'},
 {'key': 'W7BE45A9',
  'itemType': 'book',
  'mainCreator': 'Kemp',
  'year': 2006,
  'title': 'Ancient Egypt: Anatomy of a Civilisation'},
 {'key': 'RIU459AT',
  'itemType': 'bookSection',
  'mainCreator': 'Kazhdan_Cavallo',
  'year': 1997,
  'title': 'The Peasantry'},
 {'key': 'GVIZDIC9',
  'itemType': 'book',
  'mainCreator': 'Hindle',
  'year': 2002,
  'title': 'The State and Social Change in Early Modern England, 1550–1640'},
 {'key': 'QVUNFME7',
  'itemType': 'encyclopediaArticle',
  'mainCreator': 'Boyce',
  'year': 2009,
  'title': 'NOWRUZ i. In the Pre-Islamic Period'},
 {'key': 'GKKDBU7A',
  'itemType': 'book',
  'mainCreator': 'Christian',
  'year': 1998,
  'title': 'A History of Russia, Central Asia and Mongolia. Vol. 1, Inner Eurasia from Prehistory to the Mongol Empire'},
 {'key': 'FWP9WQKM',
  'itemType': 'encyclopediaArticle',
  'mainCreator': 'Shapur_Shahbazi',
  'year': 2009,
  'title': 'NOWRUZ ii. In the Islamic Period'},
 {'key': '7DHGUJFS',
  'itemType': 'book',
  'mainCreator': 'Picken',
  'year': 2010,
  'title': 'Historical Dictionary of Shinto'},
 {'key': 'CA79XJN7',
  'itemType': 'book',
  'mainCreator': 'Nelson',
  'year': 1996,
  'title': 'A Year in the Life of a Shinto Shrine'},
 {'key': '4K7XR6DH',
  'itemType': 'book',
  'mainCreator': 'Muir',
  'year': 2005,
  'title': 'Ritual in Early Modern Europe'},
 {'key': '9C96RFZQ',
  'itemType': 'bookSection',
  'mainCreator': 'Stark_Schwartz_Nichols',
  'year': 2010,
  'title': 'From Funan to Angkor: Collapse and Regeneration in Ancient Cambodia'},
 {'key': '5STIBEUN',
  'itemType': 'bookSection',
  'mainCreator': 'Cohen_Cohen',
  'year': 2006,
  'title': 'Alexandreia Near Egypt'},
 {'key': '5RCU9B2R',
  'itemType': 'book',
  'mainCreator': 'Naquin_Rawski',
  'year': 1987,
  'title': 'Chinese Society in the Eighteenth Century'},
 {'key': '9UBNRNE7',
  'itemType': 'bookSection',
  'mainCreator': 'Halstead_Pollock',
  'year': 2015,
  'title': 'Food and Fodder in Neolithic-Bronze Age Greece. Commensality and the Construction of Value'},
 {'key': 'N3VM8I59',
  'itemType': 'bookSection',
  'mainCreator': 'Cook_Cook_Major',
  'year': 1999,
  'title': 'The Ideology of the Chu Ruling Class: Ritual Rhetoric and Bronze Inscriptions'},
 {'key': 'K2PBQGDW',
  'itemType': 'book',
  'mainCreator': 'Debrunner',
  'year': 1961,
  'title': 'Witchcraft in Ghana: A Study on the Belief in Destructive Witches and Its Effect on the Akan Tribes'},
 {'key': 'U2BANZVR',
  'itemType': 'book',
  'mainCreator': 'Shinar',
  'year': 2004,
  'title': 'Modern Islam in the Maghrib'},
 {'key': 'Q8SFU4EV',
  'itemType': 'book',
  'mainCreator': 'Hopton',
  'year': 2007,
  'title': 'Pistols at Dawn: A History of Duelling'},
 {'key': 'D2KEIVTF',
  'itemType': 'book',
  'mainCreator': 'Briggs',
  'year': 1998,
  'title': 'Early Modern France 1560-1715'},
 {'key': 'KCNCMGD6',
  'itemType': 'book',
  'mainCreator': "'I'i_Kawena_Pukui",
  'year': 1959,
  'title': 'Fragments of Hawaiian History'},
 {'key': 'BZFEUFCP',
  'itemType': 'book',
  'mainCreator': 'Schneider',
  'year': 2011,
  'title': 'An Introduction to Ancient Mesopotamian Religion'},
 {'key': 'C8RTIZXV',
  'itemType': 'book',
  'mainCreator': 'Clarence-Smith',
  'year': 2006,
  'title': 'Islam and the Abolition of Slavery'},
 {'key': 'ZWFVP6XS',
  'itemType': 'book',
  'mainCreator': 'Heather',
  'year': 1998,
  'title': 'The Goths'},
 {'key': 'H2R9QRKZ',
  'itemType': 'book',
  'mainCreator': 'James',
  'year': 1993,
  'title': 'The World of the Celts'},
 {'key': 'B55DJHUQ',
  'itemType': 'journalArticle',
  'mainCreator': 'Endicott-West',
  'year': 1986,
  'title': 'Imperial Governance in Yüan Times'},
 {'key': '3DVKJ4V5',
  'itemType': 'book',
  'mainCreator': 'Garland',
  'year': 1985,
  'title': 'The Greek way of death'},
 {'key': '7V38REAF',
  'itemType': 'book',
  'mainCreator': 'McNaughton',
  'year': 1988,
  'title': 'The Mande Blacksmiths: Knowledge, Power, and Art in West Africa'},
 {'key': 'E7VF7WDE',
  'itemType': 'journalArticle',
  'mainCreator': 'Hamilakis',
  'year': 1999,
  'title': 'Food technologies/technologies of the body: The social context of wine and oil production and consumption in Bronze Age Crete'},
 {'key': 'MB8CTM49',
  'itemType': 'book',
  'mainCreator': 'Picken',
  'year': 1994,
  'title': 'Essentials of Shinto: An Analytical Guide to Principal Teachings'},
 {'key': 'UVDACXEA',
  'itemType': 'book',
  'mainCreator': 'Bodde',
  'year': 1975,
  'title': 'Festivals in Classical China: New Year and Other Annual Observances During the Han Dynasty, 206 B.C.-A.D. 220'},
 {'key': 'MFW8ARZG',
  'itemType': 'journalArticle',
  'mainCreator': 'Manzon',
  'year': 2013,
  'title': 'Humans and Things: Mande "Fetishes" as Subjects'},
 {'key': '4D6E72FK',
  'itemType': 'book',
  'mainCreator': 'Ebrey',
  'year': 1991,
  'title': 'Confucianism and Family Rituals in Imperial China: A Social History of Writing about Rites'},
 {'key': 'Z7XT6949',
  'itemType': 'book',
  'mainCreator': 'Hsu_Linduff',
  'year': 1988,
  'title': 'Western Chou Civilization'},
 {'key': '4VRXQDTV',
  'itemType': 'book',
  'mainCreator': 'Miksic',
  'year': 1990,
  'title': 'Old Javanese Gold'},
 {'key': 'T43NUQ8V',
  'itemType': 'book',
  'mainCreator': 'Aslan',
  'year': 2005,
  'title': 'No God But God: The Origins, Evolution and Future of Islam'},
 {'key': 'QJ4Z7AAB',
  'itemType': 'book',
  'mainCreator': 'Kuykendall',
  'year': 1938,
  'title': 'The Hawaiian Kingdom'},
 {'key': '8PDJ3388',
  'itemType': 'book',
  'mainCreator': 'Ellis',
  'year': 1998,
  'title': 'The Ancient World of the Celts'},
 {'key': '8B2MWN4V',
  'itemType': 'journalArticle',
  'mainCreator': 'Knappett_Schoep',
  'year': 2000,
  'title': 'Continuity and change in Minoan palatial power'},
 {'key': 'C5TGID8G',
  'itemType': 'book',
  'mainCreator': 'Hägg_Μαρινάτου',
  'year': 1987,
  'title': 'The Function of the Minoan Palaces: Proceedings of the Fourth International Symposium at the Swedish Institute in Athens, 10-16 June, 1984'},
 {'key': 'ANJUAT66',
  'itemType': 'book',
  'mainCreator': 'Shaw',
  'year': 2009,
  'title': 'Minoan Architecture: Materials and Techniques'},
 {'key': 'XX5ESCN5',
  'itemType': 'book',
  'mainCreator': 'Driessen_Schoep_Laffineur',
  'year': 2002,
  'title': 'Monuments of Minos: rethinking the Minoan Palaces ; proceedings of the international workshop "Crete of the hundred palaces?" held at the Université Catholique de Louvain, Louvain-la-Neuve, 14-15 December 2001'},
 {'key': '3IMZR49J',
  'itemType': 'bookSection',
  'mainCreator': 'Stefanakis_Chaniotis',
  'year': 1999,
  'title': 'The introduction of coinage in Crete and the beginning of local minting'},
 {'key': 'VNPJ9CPU',
  'itemType': 'book',
  'mainCreator': 'Sanders',
  'year': 1982,
  'title': 'Roman Crete: An Archaeological Survey and Gazetteer of Late Hellenistic, Roman and Early Byzantine Crete'},
 {'key': '3HAJ49PE',
  'itemType': 'journalArticle',
  'mainCreator': 'Rethemiotakis_Christakis',
  'year': 2011,
  'title': 'Landscapes of power in Protopalatial Crete: new evidence from Galatas, Pediada'},
 {'key': 'RZ2UFBPR',
  'itemType': 'book',
  'mainCreator': 'Nowicki',
  'year': 2000,
  'title': 'Defensible Sites in Crete, C. 1200-800 B.C.: LM IIIB/IIIC Through Early Geometric'},
 {'key': 'HFIX5IVD',
  'itemType': 'book',
  'mainCreator': 'Willetts',
  'year': 1967,
  'title': 'The Law Code of Gortyn: Edited with Introduction, Translation and a Commentary'},
 {'key': '5XQV83IE',
  'itemType': 'journalArticle',
  'mainCreator': 'Barber_Newell_Smithsonian_Libraries',
  'year': 0,
  'title': 'Speaking out: dissent and creativity in the colonial era and beyond'},
 {'key': 'PTN8I6W4',
  'itemType': 'book',
  'mainCreator': 'Amphlett',
  'year': 2003,
  'title': 'Hats: A History of Fashion in Headwear'},
 {'key': '22M86AUH',
  'itemType': 'journalArticle',
  'mainCreator': 'Wilks',
  'year': 1957,
  'title': 'The Rise of the Akwamu Empire, 1650-1710'},
 {'key': 'NEQAVV3A',
  'itemType': 'journalArticle',
  'mainCreator': 'McCaskie',
  'year': 1983,
  'title': 'Accumulation, wealth and belief in Asante history: I. To the close of the nineteenth century'},
 {'key': 'U6V4SWX2',
  'itemType': 'book',
  'mainCreator': 'Potter',
  'year': 2008,
  'title': 'Renaissance France at War: Armies, Culture and Society, C.1480-1560'},
 {'key': 'GEWGEKCS',
  'itemType': 'book',
  'mainCreator': 'Panton',
  'year': 2015,
  'title': 'Historical Dictionary of the British Empire'},
 {'key': 'DGRETPXI',
  'itemType': 'book',
  'mainCreator': 'Office',
  'year': 2021,
  'title': 'Census of the British Empire. 1901. Report With Summary and Detailed Tables for the Several Colonies, &c., Area, Houses, and Population; Also Populati'},
 {'key': 'JMKS4D5N',
  'itemType': 'book',
  'mainCreator': 'Barthorp',
  'year': 1988,
  'title': 'The British Army on Campaign. 1856-1881'},
 {'key': '87UWBAXF',
  'itemType': 'book',
  'mainCreator': 'Wilkinson-Latham',
  'year': 1977,
  'title': 'The Boer War'},
 {'key': 'KRC59PRJ',
  'itemType': 'book',
  'mainCreator': 'Chartrand',
  'year': 1996,
  'title': "Louis XV's Army (1) Cavalry and Dragoons"},
 {'key': 'J6K3RQ3T',
  'itemType': 'book',
  'mainCreator': 'Chartrand',
  'year': 1997,
  'title': "Louis XV's Army (3) Foreign Infantry"},
 {'key': 'JRMN8EMT',
  'itemType': 'book',
  'mainCreator': 'Chartrand',
  'year': 1997,
  'title': "Louis XV's Army (2) French Infantry"},
 {'key': 'R5JM2PGZ',
  'itemType': 'book',
  'mainCreator': 'Murray',
  'year': 2009,
  'title': 'The Library: An Illustrated History'},
 {'key': 'W7ED3I8H',
  'itemType': 'bookSection',
  'mainCreator': 'Van_Berkel_et_al',
  'year': 2013,
  'title': 'The Bureaucracy'},
 {'key': '7JE2KURE',
  'itemType': 'journalArticle',
  'mainCreator': 'Love',
  'year': 2005,
  'title': '"A Princelike Soldier and Soldierlike Prince": Contemporary Views of the Military Leadership of Henry IV'},
 {'key': 'IV8F9R3R',
  'itemType': 'book',
  'mainCreator': 'Davila_et_al',
  'year': 1678,
  'title': 'The history of the civil wars of France'},
 {'key': 'B5P3G6CW',
  'itemType': 'journalArticle',
  'mainCreator': 'Lynn',
  'year': 1985,
  'title': 'Tactical Evolution in the French Army, 1560-1660'},
 {'key': 'UWC5EWCZ',
  'itemType': 'book',
  'mainCreator': 'Lynn',
  'year': 1997,
  'title': 'Giant of the Grand Siècle: The French Army, 1610-1715'},
 {'key': 'BIJS988W',
  'itemType': 'book',
  'mainCreator': 'Boorn',
  'year': 2014,
  'title': 'The Duties Of The Vizier: Civil Administration in the Early New Kingdom'},
 {'key': 'JG6M7JRF',
  'itemType': 'book',
  'mainCreator': 'Wilkinson',
  'year': 2002,
  'title': 'Genesis of the Pharaohs: Dramatic New Discoveries That Rewrite the Origins of Ancient Egypt by Toby A. H. Wilkinson (7-Apr-2003) Hardcover'},
 {'key': 'GDCHKNFS',
  'itemType': 'book',
  'mainCreator': 'Kahl',
  'year': 1994,
  'title': 'Das System der ägyptischen Hieroglyphenschrift in der 0.–3. Dynastie'},
 {'key': 'A8JNKFC3',
  'itemType': 'book',
  'mainCreator': 'Adams_Hoffman',
  'year': 1987,
  'title': 'The Fort Cemetery at Hierakonpolis: Excavated by John Garstang'},
 {'key': 'DFJ6PVPQ',
  'itemType': 'webpage',
  'mainCreator': 'Connolly',
  'year': 2017,
  'title': 'Yale archaeologists discover earliest monumental Egyptian hieroglyphs'},
 {'key': 'PBGMDN9S',
  'itemType': 'bookSection',
  'mainCreator': 'Yun_Steinhardt',
  'year': 2002,
  'title': 'Introduction, Part II'},
 {'key': 'VUJAWTNK',
  'itemType': 'bookSection',
  'mainCreator': 'Xujie_Steinhardt',
  'year': 2002,
  'title': 'The Qin and Han Dynasties'},
 {'key': 'KU4VGKEV',
  'itemType': 'book',
  'mainCreator': 'Chang_et_al',
  'year': 2005,
  'title': 'The Formation of Chinese Civilization: An Archaeological Perspective'},
 {'key': 'UMRGZUA7',
  'itemType': 'book',
  'mainCreator': 'Asbridge',
  'year': 2012,
  'title': 'The Crusades: The War for the Holy Land'},
 {'key': 'GWR5CG3V',
  'itemType': 'book',
  'mainCreator': 'Nielsen',
  'year': 1999,
  'title': 'The Domestic Mode of Production - and Beyond: An Archaeological Inquiry Into Urban Trends in Denmark, Iceland and Predynastic Egypt'},
 {'key': 'VVQ5JSWI',
  'itemType': 'book',
  'mainCreator': 'Woolley',
  'year': 2016,
  'title': 'Celestial Empire: Life in China, 1644-1911'},
 {'key': '2RBWDZU9',
  'itemType': 'book',
  'mainCreator': 'Gu',
  'year': 2019,
  'title': 'The Hidden Land: The Garrison System And the Ming Dynasty'},
 {'key': '5QJ5CBXA',
  'itemType': 'book',
  'mainCreator': 'Glahn',
  'year': 1996,
  'title': 'Fountain of Fortune: Money and Monetary Policy in China, 1000-1700'},
 {'key': 'V5QMVJGC',
  'itemType': 'book',
  'mainCreator': 'Avery',
  'year': 2003,
  'title': 'The Tea Road: China and Russia Meet Across the Steppe'},
 {'key': '9C4TGSE8',
  'itemType': 'book',
  'mainCreator': 'Chen',
  'year': 2018,
  'title': 'Zinc for Coin and Brass: Bureaucrats, Merchants, Artisans, and Mining Laborers in Qing China, ca. 1680s–1830s'},
 {'key': 'MQQVXPVT',
  'itemType': 'journalArticle',
  'mainCreator': 'Laichen',
  'year': 2003,
  'title': 'Military Technology Transfers from Ming China and the Emergence of Northern Mainland Southeast Asia (c. 1390–1527)'},
 {'key': 'U5HIQGEI',
  'itemType': 'book',
  'mainCreator': 'Faust',
  'year': 2016,
  'title': 'The Rise and Fall of the Ming Dynasty'},
 {'key': 'XGAUGNA5',
  'itemType': 'book',
  'mainCreator': 'Coyet',
  'year': 1975,
  'title': "Neglected Formosa: A Translation from the Dutch of Frederic Coyett's Verwaerloosde Formosa"},
 {'key': '9NECXWD5',
  'itemType': 'book',
  'mainCreator': 'Brook',
  'year': 1998,
  'title': 'The Confusions of Pleasure: Commerce and Culture in Ming China'},
 {'key': 'QTI79LX9',
  'itemType': 'email',
  'mainCreator': 'Miksic',
  'title': 'Email Conversation (to be taken care of)',
  'year': 2022}]