# Generated by Django 4.0.3 on 2023-12-06 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Religion',
            new_name='A_religion',
        ),
        migrations.AlterModelOptions(
            name='a_religion',
            options={'ordering': ['name']},
        ),
    ]
