# Generated by Django 4.0.3 on 2023-12-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rt', '0004_alter_gov_dis_rel_grp_occ_fun_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elites_religion',
            old_name='elites_religion',
            new_name='coded_value',
        ),
        migrations.RenameField(
            model_name='official_religion',
            old_name='official_religion',
            new_name='coded_value',
        ),
    ]
