# Generated by Django 4.0.3 on 2022-03-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisisdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='population',
            name='total_population',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
