# Generated by Django 4.0.3 on 2022-04-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisisdb', '0007_alter_examination_examination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate_of_return',
            name='rate_of_return',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
    ]
