# Generated by Django 4.0.3 on 2022-06-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisisdb', '0010_total_revenue_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annual_wages',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UNK', 'Unknown')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='balance',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UNK', 'Unknown')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='diding_taxes',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UNK', 'Unknown')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='disease_event',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UNK', 'Unknown')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='examination',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UNK', 'Unknown')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='famine_event',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UNK', 'Unknown')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='gdp_growth_rate',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UNK', 'Unknown')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='gdp_per_capita',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UNK', 'Unknown')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='gdp_total',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UNK', 'Unknown')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='jinshi_degrees_awarded',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UNK', 'Unknown')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='land_taxes_collected',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UNK', 'Unknown')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='land_yield',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UNK', 'Unknown')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='lijin',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UNK', 'Unknown')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='maritime_custom',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UNK', 'Unknown')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='misc_incomes',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UNK', 'Unknown')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='other_incomes',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UNK', 'Unknown')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='population',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UNK', 'Unknown')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='rate_of_gdp_per_capita_growth',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UNK', 'Unknown')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='rate_of_return',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UNK', 'Unknown')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='revenue_official',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UNK', 'Unknown')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='revenue_real',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UNK', 'Unknown')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='salt_tax',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UNK', 'Unknown')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='shares_of_world_gdp',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UNK', 'Unknown')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='taiping_rebellion',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UNK', 'Unknown')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='tariff_and_transit',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UNK', 'Unknown')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='total_economic_output',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UNK', 'Unknown')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='total_expenditure',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UNK', 'Unknown')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='total_revenue',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UNK', 'Unknown')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='total_tax',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UNK', 'Unknown')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='wages',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UNK', 'Unknown')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='worker_wage',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred'), ('UNK', 'Unknown')], default='TRS', max_length=5),
        ),
    ]
