# Generated by Django 4.0.3 on 2022-09-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crisisdb', '0020_alter_external_conflict_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='external_conflict',
            name='citations',
        ),
        migrations.RemoveField(
            model_name='external_conflict',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='external_conflict',
            name='description',
        ),
        migrations.RemoveField(
            model_name='external_conflict',
            name='finalized',
        ),
        migrations.RemoveField(
            model_name='external_conflict',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='external_conflict',
            name='note',
        ),
        migrations.RemoveField(
            model_name='external_conflict',
            name='polity',
        ),
        migrations.RemoveField(
            model_name='external_conflict',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='external_conflict',
            name='year_from',
        ),
        migrations.RemoveField(
            model_name='external_conflict',
            name='year_to',
        ),
    ]
