# Generated by Django 4.0.3 on 2022-09-30 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_seshat_expert_role'),
        ('crisisdb', '0024_arable_land_curator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arable_land',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.seshat_expert'),
        ),
    ]
