# Generated by Django 4.0.3 on 2022-09-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_seshat_expert_role'),
        ('crisisdb', '0026_remove_arable_land_curator_arable_land_curator'),
    ]

    operations = [
        migrations.AddField(
            model_name='agricultural_population',
            name='curator',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='accounts.seshat_expert'),
        ),
        migrations.AddField(
            model_name='arable_land_per_farmer',
            name='curator',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='accounts.seshat_expert'),
        ),
        migrations.AddField(
            model_name='crop_failure_event',
            name='curator',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='accounts.seshat_expert'),
        ),
        migrations.AddField(
            model_name='disease_outbreak',
            name='curator',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='accounts.seshat_expert'),
        ),
        migrations.AddField(
            model_name='drought_event',
            name='curator',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='accounts.seshat_expert'),
        ),
        migrations.AddField(
            model_name='external_conflict',
            name='curator',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='accounts.seshat_expert'),
        ),
        migrations.AddField(
            model_name='external_conflict_side',
            name='curator',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='accounts.seshat_expert'),
        ),
        migrations.AddField(
            model_name='famine_event',
            name='curator',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='accounts.seshat_expert'),
        ),
        migrations.AddField(
            model_name='gdp_per_capita',
            name='curator',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='accounts.seshat_expert'),
        ),
        migrations.AddField(
            model_name='gross_grain_shared_per_agricultural_population',
            name='curator',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='accounts.seshat_expert'),
        ),
        migrations.AddField(
            model_name='internal_conflict',
            name='curator',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='accounts.seshat_expert'),
        ),
        migrations.AddField(
            model_name='locust_event',
            name='curator',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='accounts.seshat_expert'),
        ),
        migrations.AddField(
            model_name='military_expense',
            name='curator',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='accounts.seshat_expert'),
        ),
        migrations.AddField(
            model_name='net_grain_shared_per_agricultural_population',
            name='curator',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='accounts.seshat_expert'),
        ),
        migrations.AddField(
            model_name='silver_inflow',
            name='curator',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='accounts.seshat_expert'),
        ),
        migrations.AddField(
            model_name='silver_stock',
            name='curator',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='accounts.seshat_expert'),
        ),
        migrations.AddField(
            model_name='socioeconomic_turmoil_event',
            name='curator',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='accounts.seshat_expert'),
        ),
        migrations.AddField(
            model_name='surplus',
            name='curator',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='accounts.seshat_expert'),
        ),
        migrations.AddField(
            model_name='total_population',
            name='curator',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='accounts.seshat_expert'),
        ),
        migrations.AlterField(
            model_name='arable_land',
            name='curator',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='accounts.seshat_expert'),
        ),
    ]
