# Generated by Django 4.0.3 on 2022-10-04 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crisisdb', '0032_agricultural_population_comment_arable_land_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agricultural_population',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='arable_land',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='arable_land_per_farmer',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='crop_failure_event',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='disease_outbreak',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='drought_event',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='external_conflict',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='external_conflict_side',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='famine_event',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='gdp_per_capita',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='gross_grain_shared_per_agricultural_population',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='internal_conflict',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='locust_event',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='military_expense',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='net_grain_shared_per_agricultural_population',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='silver_inflow',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='silver_stock',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='socioeconomic_turmoil_event',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='surplus',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='total_population',
            name='comment',
        ),
    ]
