# Generated by Django 4.0.3 on 2023-01-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisisdb', '0040_alter_human_sacrifice_human_sacrifice'),
    ]

    operations = [
        migrations.AddField(
            model_name='human_sacrifice',
            name='drb_reviewed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='human_sacrifice',
            name='expert_reviewed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='human_sacrifice',
            name='human_sacrifice',
            field=models.CharField(choices=[('U', 'Unknown'), ('A;P', 'Scholarly Disagreement'), ('P*', 'Present'), ('P', 'Inferred Present'), ('A~P', 'Transitional Period <br> <span class="text-secondary">(from Absent to Present)</span>'), ('A', 'Absent'), ('A*', 'Inferred Absent'), ('P~A', 'Transitional Period <br> <span class="text-secondary">(from Present to Absent)')], max_length=500),
        ),
    ]
