# Generated by Django 4.0.3 on 2023-01-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisisdb', '0042_alter_human_sacrifice_expert_reviewed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='human_sacrifice',
            options={'ordering': ['year_from', 'year_to'], 'verbose_name': 'Human_sacrifice', 'verbose_name_plural': 'Human_sacrifices'},
        ),
        migrations.AlterField(
            model_name='agricultural_population',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='arable_land',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='arable_land_per_farmer',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='crop_failure_event',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='disease_outbreak',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='drought_event',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='external_conflict',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='external_conflict_side',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='famine_event',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='gdp_per_capita',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='gross_grain_shared_per_agricultural_population',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='human_sacrifice',
            name='human_sacrifice',
            field=models.CharField(choices=[('U', 'Unknown'), ('A;P', 'Scholarly Disagreement'), ('P', 'Present'), ('A~P', 'Transitional (Absent -> Present)'), ('A', 'Absent'), ('P~A', 'Transitional (Present -> Absent)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='human_sacrifice',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='internal_conflict',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='locust_event',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='military_expense',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='net_grain_shared_per_agricultural_population',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='silver_inflow',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='silver_stock',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='socioeconomic_turmoil_event',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='surplus',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='total_population',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Evidenced'), ('DSP', 'Disputed'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
    ]
