# Generated by Django 4.0.3 on 2023-05-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisisdb', '0049_crisis_consequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crisis_consequence',
            name='assassination',
            field=models.CharField(blank=True, choices=[('U', 'Unknown'), ('SU', 'Suspected Unknown'), ('P', 'Present'), ('A', 'Absent'), ('IP', 'Inferred Present'), ('IA', 'Inferred Absent')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='crisis_consequence',
            name='capital',
            field=models.CharField(blank=True, choices=[('U', 'Unknown'), ('SU', 'Suspected Unknown'), ('P', 'Present'), ('A', 'Absent'), ('IP', 'Inferred Present'), ('IA', 'Inferred Absent')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='crisis_consequence',
            name='century_plus',
            field=models.CharField(blank=True, choices=[('U', 'Unknown'), ('SU', 'Suspected Unknown'), ('P', 'Present'), ('A', 'Absent'), ('IP', 'Inferred Present'), ('IA', 'Inferred Absent')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='crisis_consequence',
            name='civil_war',
            field=models.CharField(blank=True, choices=[('U', 'Unknown'), ('SU', 'Suspected Unknown'), ('P', 'Present'), ('A', 'Absent'), ('IP', 'Inferred Present'), ('IA', 'Inferred Absent')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='crisis_consequence',
            name='collapse',
            field=models.CharField(blank=True, choices=[('U', 'Unknown'), ('SU', 'Suspected Unknown'), ('P', 'Present'), ('A', 'Absent'), ('IP', 'Inferred Present'), ('IA', 'Inferred Absent')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='crisis_consequence',
            name='conquest',
            field=models.CharField(blank=True, choices=[('U', 'Unknown'), ('SU', 'Suspected Unknown'), ('P', 'Present'), ('A', 'Absent'), ('IP', 'Inferred Present'), ('IA', 'Inferred Absent')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='crisis_consequence',
            name='constitution',
            field=models.CharField(blank=True, choices=[('U', 'Unknown'), ('SU', 'Suspected Unknown'), ('P', 'Present'), ('A', 'Absent'), ('IP', 'Inferred Present'), ('IA', 'Inferred Absent')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='crisis_consequence',
            name='decline',
            field=models.CharField(blank=True, choices=[('U', 'Unknown'), ('SU', 'Suspected Unknown'), ('P', 'Present'), ('A', 'Absent'), ('IP', 'Inferred Present'), ('IA', 'Inferred Absent')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='crisis_consequence',
            name='depose',
            field=models.CharField(blank=True, choices=[('U', 'Unknown'), ('SU', 'Suspected Unknown'), ('P', 'Present'), ('A', 'Absent'), ('IP', 'Inferred Present'), ('IA', 'Inferred Absent')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='crisis_consequence',
            name='downward_mobility',
            field=models.CharField(blank=True, choices=[('U', 'Unknown'), ('SU', 'Suspected Unknown'), ('P', 'Present'), ('A', 'Absent'), ('IP', 'Inferred Present'), ('IA', 'Inferred Absent')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='crisis_consequence',
            name='epidemic',
            field=models.CharField(blank=True, choices=[('U', 'Unknown'), ('SU', 'Suspected Unknown'), ('P', 'Present'), ('A', 'Absent'), ('IP', 'Inferred Present'), ('IA', 'Inferred Absent')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='crisis_consequence',
            name='extermination',
            field=models.CharField(blank=True, choices=[('U', 'Unknown'), ('SU', 'Suspected Unknown'), ('P', 'Present'), ('A', 'Absent'), ('IP', 'Inferred Present'), ('IA', 'Inferred Absent')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='crisis_consequence',
            name='fragmentation',
            field=models.CharField(blank=True, choices=[('U', 'Unknown'), ('SU', 'Suspected Unknown'), ('P', 'Present'), ('A', 'Absent'), ('IP', 'Inferred Present'), ('IA', 'Inferred Absent')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='crisis_consequence',
            name='labor',
            field=models.CharField(blank=True, choices=[('U', 'Unknown'), ('SU', 'Suspected Unknown'), ('P', 'Present'), ('A', 'Absent'), ('IP', 'Inferred Present'), ('IA', 'Inferred Absent')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='crisis_consequence',
            name='public_goods',
            field=models.CharField(blank=True, choices=[('U', 'Unknown'), ('SU', 'Suspected Unknown'), ('P', 'Present'), ('A', 'Absent'), ('IP', 'Inferred Present'), ('IA', 'Inferred Absent')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='crisis_consequence',
            name='religion',
            field=models.CharField(blank=True, choices=[('U', 'Unknown'), ('SU', 'Suspected Unknown'), ('P', 'Present'), ('A', 'Absent'), ('IP', 'Inferred Present'), ('IA', 'Inferred Absent')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='crisis_consequence',
            name='revolution',
            field=models.CharField(blank=True, choices=[('U', 'Unknown'), ('SU', 'Suspected Unknown'), ('P', 'Present'), ('A', 'Absent'), ('IP', 'Inferred Present'), ('IA', 'Inferred Absent')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='crisis_consequence',
            name='successful_revolution',
            field=models.CharField(blank=True, choices=[('U', 'Unknown'), ('SU', 'Suspected Unknown'), ('P', 'Present'), ('A', 'Absent'), ('IP', 'Inferred Present'), ('IA', 'Inferred Absent')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='crisis_consequence',
            name='suffrage',
            field=models.CharField(blank=True, choices=[('U', 'Unknown'), ('SU', 'Suspected Unknown'), ('P', 'Present'), ('A', 'Absent'), ('IP', 'Inferred Present'), ('IA', 'Inferred Absent')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='crisis_consequence',
            name='unfree_labor',
            field=models.CharField(blank=True, choices=[('U', 'Unknown'), ('SU', 'Suspected Unknown'), ('P', 'Present'), ('A', 'Absent'), ('IP', 'Inferred Present'), ('IA', 'Inferred Absent')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='crisis_consequence',
            name='uprising',
            field=models.CharField(blank=True, choices=[('U', 'Unknown'), ('SU', 'Suspected Unknown'), ('P', 'Present'), ('A', 'Absent'), ('IP', 'Inferred Present'), ('IA', 'Inferred Absent')], max_length=5, null=True),
        ),
    ]
