# Generated by Django 4.0.3 on 2023-10-06 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisisdb', '0058_alter_power_transition_predecessor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Us_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=300, null=True)),
                ('county', models.CharField(blank=True, max_length=300, null=True)),
                ('special_place', models.CharField(blank=True, max_length=300, null=True)),
                ('us_state', models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('UNK', 'UNKNOWN')], max_length=5, null=True)),
                ('attention_tag', models.CharField(blank=True, choices=[('NeedsExpertInput', 'Needs Expert Input'), ('IsInconsistent', 'Is Inconsistent'), ('IsWrong', 'Is Wrong'), ('IsOk', 'IS OK')], max_length=30, null=True)),
            ],
            options={
                'ordering': ['us_state', 'city', 'county', 'special_place'],
            },
        ),
        migrations.CreateModel(
            name='Us_violence_data_source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=20, null=True)),
                ('is_uncertain', models.BooleanField(default=False)),
                ('attention_tag', models.CharField(blank=True, choices=[('NeedsExpertInput', 'Needs Expert Input'), ('IsInconsistent', 'Is Inconsistent'), ('IsWrong', 'Is Wrong'), ('IsOk', 'IS OK')], max_length=30, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Us_violence_subtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('is_uncertain', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Us_violence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violence_date', models.DateField(blank=True, null=True)),
                ('violence_type', models.CharField(blank=True, max_length=80, null=True)),
                ('fatalities', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('source_details', models.TextField(blank=True, null=True)),
                ('narrative', models.TextField(blank=True, null=True)),
                ('location', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='crisisdb.us_location')),
                ('short_data_source', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='crisisdb.us_violence_data_source')),
                ('violence_subtype', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='crisisdb.us_violence_subtype')),
            ],
            options={
                'ordering': ['violence_date', 'fatalities'],
            },
        ),
    ]
