# Generated by Django 4.0.3 on 2023-10-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisisdb', '0059_us_location_us_violence_data_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='us_violence',
            name='violence_type',
            field=models.CharField(blank=True, choices=[('lynching', 'lynching'), ('riot', 'riot'), ('executions', 'executions'), ('war', 'war'), ('assassination', 'assassination'), ('compilation', 'compilation'), ('terrorism', 'terrorism'), ('rampage', 'rampage'), ('insurrection', 'insurrection'), ('mass suicide', 'mass suicide'), ('UNKNOWN_INPUT', 'UNKNOWN_INPUT'), ('unknown', 'unknown'), ('revenge', 'revenge')], max_length=50, null=True),
        ),
    ]
