# Generated by Django 4.0.3 on 2023-10-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisisdb', '0061_alter_us_location_options_alter_us_violence_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='us_violence_data_source',
            name='url_address',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
