# Generated by Django 4.0.3 on 2024-03-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisisdb', '0064_alter_us_violence_violence_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agricultural_population',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='arable_land',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='arable_land_per_farmer',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='crisis_consequence',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='crop_failure_event',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='disease_outbreak',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='drought_event',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='external_conflict',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='external_conflict_side',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='famine_event',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='gdp_per_capita',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='gross_grain_shared_per_agricultural_population',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='human_sacrifice',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='internal_conflict',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='locust_event',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='military_expense',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='net_grain_shared_per_agricultural_population',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='power_transition',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='silver_inflow',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='silver_stock',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='socioeconomic_turmoil_event',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='surplus',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
        migrations.AlterField(
            model_name='total_population',
            name='tag',
            field=models.CharField(choices=[('TRS', 'Confident'), ('SSP', 'Suspected'), ('IFR', 'Inferred')], default='TRS', max_length=5),
        ),
    ]
